var bazaOsob= { osoba:[
  {
    "imie": "Billie",
    "nazwisko": "Cantu",
    "nazwiskoRodowe": "Villarreal",
    "nrDomu": 69,
    "ulica": "Prospect Avenue",
    "kod": "97-822",
    "miasto": "Jacksonburg",
    "dataUrodzenia": "27.11.1934",
    "miejsceUrodzenia": "Washington",
    "PESEL": 66061941590,
    "NIP": 7400054015,
    "imieOjca": "Pansy",
    "imieMatki": "Claire",
    "plec": "female",
    "nazwiskoMatki": "Chandler",
    "rodzajDokumentuTozsamosci": "dowod osobisty",
    "wydanyPrzez": "BurmistrzX",
    "nrDokumentu": "XYZ969299",
    "email": "clairechandler@crustatia.com",
    "telefon": "(975) 429-3270",
    "wyksztalcenie": "wyższe",
    "obywatelstwo": "francuskie",
    "narodowosc": "Vatican City State (Holy See)"
  },
  {
    "imie": "Alma",
    "nazwisko": "Copeland",
    "nazwiskoRodowe": "Slater",
    "nrDomu": 196,
    "ulica": "Aitken Place",
    "kod": "35-577",
    "miasto": "Clay",
    "dataUrodzenia": "9.10.1948",
    "miejsceUrodzenia": "Strykersville",
    "PESEL": 68022564932,
    "NIP": 9196071922,
    "imieOjca": "Noble",
    "imieMatki": "Kellie",
    "plec": "female",
    "nazwiskoMatki": "Leblanc",
    "rodzajDokumentuTozsamosci": "dowod osobisty",
    "wydanyPrzez": "BurmistrzX",
    "nrDokumentu": "XYZ627542",
    "email": "kellieleblanc@crustatia.com",
    "telefon": "(957) 478-2522",
    "wyksztalcenie": "gimnazjalne",
    "obywatelstwo": "francuskie",
    "narodowosc": "Tonga"
  },
  {
    "imie": "Rios",
    "nazwisko": "Morales",
    "nazwiskoRodowe": "Merrill",
    "nrDomu": 165,
    "ulica": "Strauss Street",
    "kod": "33-135",
    "miasto": "Wadsworth",
    "dataUrodzenia": "19.5.1973",
    "miejsceUrodzenia": "Berlin",
    "PESEL": 20053049359,
    "NIP": 1799460579,
    "imieOjca": "Rosario",
    "imieMatki": "Sheree",
    "plec": "female",
    "nazwiskoMatki": "Lopez",
    "rodzajDokumentuTozsamosci": "dowod osobisty",
    "wydanyPrzez": "BurmistrzX",
    "nrDokumentu": "XYZ169930",
    "email": "shereelopez@crustatia.com",
    "telefon": "(833) 493-2140",
    "wyksztalcenie": "podstawowe",
    "obywatelstwo": "francuskie",
    "narodowosc": "Romania"
  },
  {
    "imie": "Mae",
    "nazwisko": "Perez",
    "nazwiskoRodowe": "Vincent",
    "nrDomu": 179,
    "ulica": "Stone Avenue",
    "kod": "51-250",
    "miasto": "Bennett",
    "dataUrodzenia": "17.10.1907",
    "miejsceUrodzenia": "Detroit",
    "PESEL": 65082524289,
    "NIP": 3363605337,
    "imieOjca": "Santana",
    "imieMatki": "Lott",
    "plec": "male",
    "nazwiskoMatki": "Fleming",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ366005",
    "email": "lottfleming@crustatia.com",
    "telefon": "(986) 539-2897",
    "wyksztalcenie": "zasadnicze zawodowe",
    "obywatelstwo": "niemieckie",
    "narodowosc": "Namibia"
  },
  {
    "imie": "Elma",
    "nazwisko": "Koch",
    "nazwiskoRodowe": "Reynolds",
    "nrDomu": 165,
    "ulica": "Cumberland Walk",
    "kod": "45-668",
    "miasto": "Vivian",
    "dataUrodzenia": "29.12.1943",
    "miejsceUrodzenia": "Dargan",
    "PESEL": 54021071233,
    "NIP": 4972311976,
    "imieOjca": "Lola",
    "imieMatki": "Moses",
    "plec": "male",
    "nazwiskoMatki": "Sherman",
    "rodzajDokumentuTozsamosci": "dowod osobisty",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ756246",
    "email": "mosessherman@crustatia.com",
    "telefon": "(808) 547-3356",
    "wyksztalcenie": "zasadnicze zawodowe",
    "obywatelstwo": "francuskie",
    "narodowosc": "Panama"
  },
  {
    "imie": "Dena",
    "nazwisko": "Brown",
    "nazwiskoRodowe": "Rush",
    "nrDomu": 154,
    "ulica": "Mersereau Court",
    "kod": "90-675",
    "miasto": "Wilmington",
    "dataUrodzenia": "12.10.1957",
    "miejsceUrodzenia": "Summerfield",
    "PESEL": 74061013269,
    "NIP": 6199674141,
    "imieOjca": "Bettye",
    "imieMatki": "Kemp",
    "plec": "male",
    "nazwiskoMatki": "Rich",
    "rodzajDokumentuTozsamosci": "dowod osobisty",
    "wydanyPrzez": "BurmistrzZ",
    "nrDokumentu": "XYZ642387",
    "email": "kemprich@crustatia.com",
    "telefon": "(866) 422-3602",
    "wyksztalcenie": "zasadnicze zawodowe",
    "obywatelstwo": "niemieckie",
    "narodowosc": "Czech Republic"
  },
  {
    "imie": "Lessie",
    "nazwisko": "Knowles",
    "nazwiskoRodowe": "Wilkins",
    "nrDomu": 34,
    "ulica": "Wolcott Street",
    "kod": "68-305",
    "miasto": "Oretta",
    "dataUrodzenia": "20.6.1973",
    "miejsceUrodzenia": "Oasis",
    "PESEL": 85012519543,
    "NIP": 5438512123,
    "imieOjca": "Hale",
    "imieMatki": "Patrica",
    "plec": "female",
    "nazwiskoMatki": "Cooley",
    "rodzajDokumentuTozsamosci": "dowod osobisty",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ850266",
    "email": "patricacooley@crustatia.com",
    "telefon": "(882) 513-2352",
    "wyksztalcenie": "średnie",
    "obywatelstwo": "francuskie",
    "narodowosc": "Martinique"
  },
  {
    "imie": "Bonner",
    "nazwisko": "Wright",
    "nazwiskoRodowe": "Wood",
    "nrDomu": 41,
    "ulica": "Bristol Street",
    "kod": "21-457",
    "miasto": "Cumminsville",
    "dataUrodzenia": "29.3.2001",
    "miejsceUrodzenia": "Bascom",
    "PESEL": 97032424745,
    "NIP": 1410172591,
    "imieOjca": "Jean",
    "imieMatki": "Melba",
    "plec": "female",
    "nazwiskoMatki": "Klein",
    "rodzajDokumentuTozsamosci": "dowod osobisty",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ862028",
    "email": "melbaklein@crustatia.com",
    "telefon": "(884) 514-2711",
    "wyksztalcenie": "średnie",
    "obywatelstwo": "niemieckie",
    "narodowosc": "Yugoslavia"
  },
  {
    "imie": "Constance",
    "nazwisko": "Kirk",
    "nazwiskoRodowe": "Collier",
    "nrDomu": 126,
    "ulica": "Preston Court",
    "kod": "90-810",
    "miasto": "Cade",
    "dataUrodzenia": "6.6.1946",
    "miejsceUrodzenia": "Gulf",
    "PESEL": 27062214228,
    "NIP": 8527194327,
    "imieOjca": "Armstrong",
    "imieMatki": "Hickman",
    "plec": "male",
    "nazwiskoMatki": "Chambers",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzZ",
    "nrDokumentu": "XYZ797574",
    "email": "hickmanchambers@crustatia.com",
    "telefon": "(897) 570-3480",
    "wyksztalcenie": "średnie",
    "obywatelstwo": "francuskie",
    "narodowosc": "Aruba"
  },
  {
    "imie": "Woodard",
    "nazwisko": "Boyer",
    "nazwiskoRodowe": "Duran",
    "nrDomu": 121,
    "ulica": "Newkirk Placez",
    "kod": "93-316",
    "miasto": "Sanford",
    "dataUrodzenia": "9.8.1994",
    "miejsceUrodzenia": "Blandburg",
    "PESEL": 12041917676,
    "NIP": 2700588720,
    "imieOjca": "Sullivan",
    "imieMatki": "Rene",
    "plec": "female",
    "nazwiskoMatki": "Meyer",
    "rodzajDokumentuTozsamosci": "paszport",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ988210",
    "email": "renemeyer@crustatia.com",
    "telefon": "(917) 435-3276",
    "wyksztalcenie": "gimnazjalne",
    "obywatelstwo": "niemieckie",
    "narodowosc": "Ukraine"
  },
  {
    "imie": "Mccall",
    "nazwisko": "Maldonado",
    "nazwiskoRodowe": "Hicks",
    "nrDomu": 139,
    "ulica": "Howard Place",
    "kod": "88-501",
    "miasto": "Leeper",
    "dataUrodzenia": "9.1.1920",
    "miejsceUrodzenia": "Hoehne",
    "PESEL": 76051863584,
    "NIP": 7994344497,
    "imieOjca": "Buchanan",
    "imieMatki": "Trevino",
    "plec": "male",
    "nazwiskoMatki": "Webster",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ602224",
    "email": "trevinowebster@crustatia.com",
    "telefon": "(935) 400-3959",
    "wyksztalcenie": "zasadnicze zawodowe",
    "obywatelstwo": "niemieckie",
    "narodowosc": "Liechtenstein"
  },
  {
    "imie": "Rose",
    "nazwisko": "Livingston",
    "nazwiskoRodowe": "Rogers",
    "nrDomu": 11,
    "ulica": "Malta Street",
    "kod": "38-436",
    "miasto": "Derwood",
    "dataUrodzenia": "2.12.1914",
    "miejsceUrodzenia": "Courtland",
    "PESEL": 86091114503,
    "NIP": 3906732190,
    "imieOjca": "Juanita",
    "imieMatki": "Freda",
    "plec": "female",
    "nazwiskoMatki": "Allison",
    "rodzajDokumentuTozsamosci": "dowod osobisty",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ851351",
    "email": "fredaallison@crustatia.com",
    "telefon": "(834) 477-3374",
    "wyksztalcenie": "wyższe",
    "obywatelstwo": "niemieckie",
    "narodowosc": "Honduras"
  },
  {
    "imie": "Gail",
    "nazwisko": "Salas",
    "nazwiskoRodowe": "Carson",
    "nrDomu": 120,
    "ulica": "Stryker Street",
    "kod": "78-504",
    "miasto": "Rockingham",
    "dataUrodzenia": "22.1.1923",
    "miejsceUrodzenia": "Brule",
    "PESEL": 87042743206,
    "NIP": 3304316659,
    "imieOjca": "Martin",
    "imieMatki": "York",
    "plec": "male",
    "nazwiskoMatki": "Dudley",
    "rodzajDokumentuTozsamosci": "paszport",
    "wydanyPrzez": "BurmistrzZ",
    "nrDokumentu": "XYZ924996",
    "email": "yorkdudley@crustatia.com",
    "telefon": "(916) 462-2477",
    "wyksztalcenie": "gimnazjalne",
    "obywatelstwo": "polskie",
    "narodowosc": "Albania"
  },
  {
    "imie": "Evans",
    "nazwisko": "Wade",
    "nazwiskoRodowe": "Dean",
    "nrDomu": 165,
    "ulica": "Fay Court",
    "kod": "87-211",
    "miasto": "Sisquoc",
    "dataUrodzenia": "15.3.1994",
    "miejsceUrodzenia": "Bancroft",
    "PESEL": 92072634976,
    "NIP": 4868665917,
    "imieOjca": "Brandi",
    "imieMatki": "Bauer",
    "plec": "male",
    "nazwiskoMatki": "Atkins",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzZ",
    "nrDokumentu": "XYZ146632",
    "email": "baueratkins@crustatia.com",
    "telefon": "(894) 439-3407",
    "wyksztalcenie": "wyższe",
    "obywatelstwo": "polskie",
    "narodowosc": "Indonesia"
  },
  {
    "imie": "Wood",
    "nazwisko": "Dorsey",
    "nazwiskoRodowe": "Gamble",
    "nrDomu": 115,
    "ulica": "Dwight Street",
    "kod": "36-471",
    "miasto": "Boling",
    "dataUrodzenia": "5.5.2010",
    "miejsceUrodzenia": "Herbster",
    "PESEL": 79051995328,
    "NIP": 7080397454,
    "imieOjca": "Blackwell",
    "imieMatki": "Snyder",
    "plec": "male",
    "nazwiskoMatki": "Bryant",
    "rodzajDokumentuTozsamosci": "paszport",
    "wydanyPrzez": "BurmistrzX",
    "nrDokumentu": "XYZ722184",
    "email": "snyderbryant@crustatia.com",
    "telefon": "(912) 536-2583",
    "wyksztalcenie": "wyższe",
    "obywatelstwo": "niemieckie",
    "narodowosc": "Singapore"
  },
  {
    "imie": "Harrington",
    "nazwisko": "Gibson",
    "nazwiskoRodowe": "Holden",
    "nrDomu": 174,
    "ulica": "Montana Place",
    "kod": "90-269",
    "miasto": "Santel",
    "dataUrodzenia": "24.7.1957",
    "miejsceUrodzenia": "Shrewsbury",
    "PESEL": 61011481682,
    "NIP": 8495390462,
    "imieOjca": "Cornelia",
    "imieMatki": "Colleen",
    "plec": "female",
    "nazwiskoMatki": "Craft",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzZ",
    "nrDokumentu": "XYZ156799",
    "email": "colleencraft@crustatia.com",
    "telefon": "(900) 504-3250",
    "wyksztalcenie": "gimnazjalne",
    "obywatelstwo": "niemieckie",
    "narodowosc": "Brunei Darussalam"
  },
  {
    "imie": "Rosalie",
    "nazwisko": "Dillon",
    "nazwiskoRodowe": "Arnold",
    "nrDomu": 70,
    "ulica": "Billings Place",
    "kod": "93-419",
    "miasto": "Glenbrook",
    "dataUrodzenia": "26.2.2011",
    "miejsceUrodzenia": "Weeksville",
    "PESEL": 12021094532,
    "NIP": 6363006860,
    "imieOjca": "Reva",
    "imieMatki": "Annie",
    "plec": "female",
    "nazwiskoMatki": "Lee",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzX",
    "nrDokumentu": "XYZ548973",
    "email": "annielee@crustatia.com",
    "telefon": "(846) 585-2842",
    "wyksztalcenie": "zasadnicze zawodowe",
    "obywatelstwo": "francuskie",
    "narodowosc": "Swaziland"
  },
  {
    "imie": "Joseph",
    "nazwisko": "Solomon",
    "nazwiskoRodowe": "Kerr",
    "nrDomu": 137,
    "ulica": "Exeter Street",
    "kod": "63-657",
    "miasto": "Remington",
    "dataUrodzenia": "20.4.2004",
    "miejsceUrodzenia": "Moscow",
    "PESEL": 10042637046,
    "NIP": 3203736998,
    "imieOjca": "Carrillo",
    "imieMatki": "Graves",
    "plec": "male",
    "nazwiskoMatki": "Daniel",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzZ",
    "nrDokumentu": "XYZ324705",
    "email": "gravesdaniel@crustatia.com",
    "telefon": "(926) 492-2946",
    "wyksztalcenie": "wyższe",
    "obywatelstwo": "francuskie",
    "narodowosc": "Mayotte"
  },
  {
    "imie": "Everett",
    "nazwisko": "Long",
    "nazwiskoRodowe": "Vang",
    "nrDomu": 85,
    "ulica": "Osborn Street",
    "kod": "90-931",
    "miasto": "Westboro",
    "dataUrodzenia": "23.7.1924",
    "miejsceUrodzenia": "Sparkill",
    "PESEL": 13082640492,
    "NIP": 4070335326,
    "imieOjca": "Amalia",
    "imieMatki": "Holden",
    "plec": "male",
    "nazwiskoMatki": "Baxter",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzZ",
    "nrDokumentu": "XYZ540452",
    "email": "holdenbaxter@crustatia.com",
    "telefon": "(836) 435-2310",
    "wyksztalcenie": "wyższe",
    "obywatelstwo": "polskie",
    "narodowosc": "Australia"
  },
  {
    "imie": "Alexandra",
    "nazwisko": "Richards",
    "nazwiskoRodowe": "Powers",
    "nrDomu": 149,
    "ulica": "Bond Street",
    "kod": "89-744",
    "miasto": "Maybell",
    "dataUrodzenia": "30.5.1968",
    "miejsceUrodzenia": "Cascades",
    "PESEL": 54011376956,
    "NIP": 1818711526,
    "imieOjca": "Lena",
    "imieMatki": "Maureen",
    "plec": "female",
    "nazwiskoMatki": "Williams",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ365332",
    "email": "maureenwilliams@crustatia.com",
    "telefon": "(813) 421-2062",
    "wyksztalcenie": "podstawowe",
    "obywatelstwo": "polskie",
    "narodowosc": "Tajikistan"
  },
  {
    "imie": "Deann",
    "nazwisko": "Phillips",
    "nazwiskoRodowe": "Ferguson",
    "nrDomu": 176,
    "ulica": "Stryker Court",
    "kod": "40-718",
    "miasto": "Balm",
    "dataUrodzenia": "3.10.1931",
    "miejsceUrodzenia": "Osmond",
    "PESEL": 48012624851,
    "NIP": 6587576719,
    "imieOjca": "Nadine",
    "imieMatki": "Buckley",
    "plec": "male",
    "nazwiskoMatki": "Foley",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzX",
    "nrDokumentu": "XYZ589887",
    "email": "buckleyfoley@crustatia.com",
    "telefon": "(992) 520-3799",
    "wyksztalcenie": "podstawowe",
    "obywatelstwo": "francuskie",
    "narodowosc": "Georgia"
  },
  {
    "imie": "Loraine",
    "nazwisko": "Mendez",
    "nazwiskoRodowe": "Wells",
    "nrDomu": 197,
    "ulica": "Lacon Court",
    "kod": "41-839",
    "miasto": "Itmann",
    "dataUrodzenia": "17.2.2004",
    "miejsceUrodzenia": "Harviell",
    "PESEL": 53062798034,
    "NIP": 8254431656,
    "imieOjca": "Brianna",
    "imieMatki": "Robyn",
    "plec": "female",
    "nazwiskoMatki": "Knox",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ612148",
    "email": "robynknox@crustatia.com",
    "telefon": "(827) 489-3636",
    "wyksztalcenie": "podstawowe",
    "obywatelstwo": "francuskie",
    "narodowosc": "Greece"
  },
  {
    "imie": "Kay",
    "nazwisko": "Donaldson",
    "nazwiskoRodowe": "Murray",
    "nrDomu": 172,
    "ulica": "Hoyt Street",
    "kod": "85-526",
    "miasto": "Slovan",
    "dataUrodzenia": "29.5.1910",
    "miejsceUrodzenia": "Shelby",
    "PESEL": 69061413366,
    "NIP": 4205697354,
    "imieOjca": "Contreras",
    "imieMatki": "Hicks",
    "plec": "male",
    "nazwiskoMatki": "Mccray",
    "rodzajDokumentuTozsamosci": "paszport",
    "wydanyPrzez": "BurmistrzZ",
    "nrDokumentu": "XYZ793106",
    "email": "hicksmccray@crustatia.com",
    "telefon": "(946) 579-3195",
    "wyksztalcenie": "zasadnicze zawodowe",
    "obywatelstwo": "polskie",
    "narodowosc": "Macau"
  },
  {
    "imie": "Floyd",
    "nazwisko": "George",
    "nazwiskoRodowe": "Good",
    "nrDomu": 79,
    "ulica": "Butler Place",
    "kod": "41-623",
    "miasto": "Cotopaxi",
    "dataUrodzenia": "10.7.2008",
    "miejsceUrodzenia": "Matthews",
    "PESEL": 60082051171,
    "NIP": 1968017674,
    "imieOjca": "Bridgett",
    "imieMatki": "Pearlie",
    "plec": "female",
    "nazwiskoMatki": "Carr",
    "rodzajDokumentuTozsamosci": "dowod osobisty",
    "wydanyPrzez": "BurmistrzZ",
    "nrDokumentu": "XYZ992057",
    "email": "pearliecarr@crustatia.com",
    "telefon": "(937) 577-3505",
    "wyksztalcenie": "gimnazjalne",
    "obywatelstwo": "polskie",
    "narodowosc": "Antigua and Barbuda"
  },
  {
    "imie": "Heather",
    "nazwisko": "Ramirez",
    "nazwiskoRodowe": "Adams",
    "nrDomu": 180,
    "ulica": "Lincoln Avenue",
    "kod": "89-682",
    "miasto": "Kent",
    "dataUrodzenia": "14.8.1920",
    "miejsceUrodzenia": "Savage",
    "PESEL": 14021166968,
    "NIP": 4583976156,
    "imieOjca": "Gregory",
    "imieMatki": "Lloyd",
    "plec": "male",
    "nazwiskoMatki": "Kidd",
    "rodzajDokumentuTozsamosci": "paszport",
    "wydanyPrzez": "BurmistrzX",
    "nrDokumentu": "XYZ605667",
    "email": "lloydkidd@crustatia.com",
    "telefon": "(810) 416-2597",
    "wyksztalcenie": "podstawowe",
    "obywatelstwo": "francuskie",
    "narodowosc": "New Zealand"
  },
  {
    "imie": "Vaughan",
    "nazwisko": "Greene",
    "nazwiskoRodowe": "Russell",
    "nrDomu": 187,
    "ulica": "Louis Place",
    "kod": "90-426",
    "miasto": "Hackneyville",
    "dataUrodzenia": "6.2.1909",
    "miejsceUrodzenia": "Hebron",
    "PESEL": 27093052805,
    "NIP": 6776024044,
    "imieOjca": "Gwendolyn",
    "imieMatki": "Christi",
    "plec": "female",
    "nazwiskoMatki": "Mccormick",
    "rodzajDokumentuTozsamosci": "dowod osobisty",
    "wydanyPrzez": "BurmistrzZ",
    "nrDokumentu": "XYZ217828",
    "email": "christimccormick@crustatia.com",
    "telefon": "(966) 405-2789",
    "wyksztalcenie": "średnie",
    "obywatelstwo": "polskie",
    "narodowosc": "Vanuatu"
  },
  {
    "imie": "Arline",
    "nazwisko": "Hopper",
    "nazwiskoRodowe": "Mosley",
    "nrDomu": 115,
    "ulica": "Windsor Place",
    "kod": "65-806",
    "miasto": "Cassel",
    "dataUrodzenia": "17.1.1933",
    "miejsceUrodzenia": "Edgar",
    "PESEL": 28082768134,
    "NIP": 7637937198,
    "imieOjca": "Betty",
    "imieMatki": "Caitlin",
    "plec": "female",
    "nazwiskoMatki": "Cote",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzX",
    "nrDokumentu": "XYZ298704",
    "email": "caitlincote@crustatia.com",
    "telefon": "(815) 523-3893",
    "wyksztalcenie": "podstawowe",
    "obywatelstwo": "polskie",
    "narodowosc": "East Timor"
  },
  {
    "imie": "Benita",
    "nazwisko": "Mcdaniel",
    "nazwiskoRodowe": "Oneil",
    "nrDomu": 150,
    "ulica": "Bedell Lane",
    "kod": "22-156",
    "miasto": "Brantleyville",
    "dataUrodzenia": "9.9.1929",
    "miejsceUrodzenia": "Hollymead",
    "PESEL": 32082136271,
    "NIP": 4008453090,
    "imieOjca": "Lenora",
    "imieMatki": "Kimberley",
    "plec": "female",
    "nazwiskoMatki": "Warren",
    "rodzajDokumentuTozsamosci": "dowod osobisty",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ145454",
    "email": "kimberleywarren@crustatia.com",
    "telefon": "(978) 574-3067",
    "wyksztalcenie": "gimnazjalne",
    "obywatelstwo": "niemieckie",
    "narodowosc": "Samoa"
  },
  {
    "imie": "Vivian",
    "nazwisko": "Smith",
    "nazwiskoRodowe": "Richardson",
    "nrDomu": 132,
    "ulica": "Wortman Avenue",
    "kod": "68-828",
    "miasto": "Lindcove",
    "dataUrodzenia": "27.10.1919",
    "miejsceUrodzenia": "Groton",
    "PESEL": 43011430092,
    "NIP": 1437793143,
    "imieOjca": "Olson",
    "imieMatki": "Berg",
    "plec": "male",
    "nazwiskoMatki": "Harrell",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzZ",
    "nrDokumentu": "XYZ896186",
    "email": "bergharrell@crustatia.com",
    "telefon": "(849) 415-3132",
    "wyksztalcenie": "podstawowe",
    "obywatelstwo": "polskie",
    "narodowosc": "Central African Republic"
  },
  {
    "imie": "Carmela",
    "nazwisko": "Herrera",
    "nazwiskoRodowe": "Hogan",
    "nrDomu": 53,
    "ulica": "Cobek Court",
    "kod": "47-224",
    "miasto": "Crisman",
    "dataUrodzenia": "18.8.1993",
    "miejsceUrodzenia": "Fingerville",
    "PESEL": 75082837525,
    "NIP": 3210083713,
    "imieOjca": "Marguerite",
    "imieMatki": "Parrish",
    "plec": "male",
    "nazwiskoMatki": "Garrison",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzX",
    "nrDokumentu": "XYZ412547",
    "email": "parrishgarrison@crustatia.com",
    "telefon": "(950) 543-3027",
    "wyksztalcenie": "zasadnicze zawodowe",
    "obywatelstwo": "polskie",
    "narodowosc": "Cape Verde"
  },
  {
    "imie": "Mildred",
    "nazwisko": "Terrell",
    "nazwiskoRodowe": "Gill",
    "nrDomu": 168,
    "ulica": "Kings Hwy",
    "kod": "38-952",
    "miasto": "Inkerman",
    "dataUrodzenia": "21.11.1957",
    "miejsceUrodzenia": "Cresaptown",
    "PESEL": 86013056855,
    "NIP": 2811993532,
    "imieOjca": "Thomas",
    "imieMatki": "Campbell",
    "plec": "male",
    "nazwiskoMatki": "Hahn",
    "rodzajDokumentuTozsamosci": "dowod osobisty",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ899023",
    "email": "campbellhahn@crustatia.com",
    "telefon": "(889) 431-2423",
    "wyksztalcenie": "podstawowe",
    "obywatelstwo": "niemieckie",
    "narodowosc": "Russian Federation"
  },
  {
    "imie": "Hancock",
    "nazwisko": "Hubbard",
    "nazwiskoRodowe": "Dale",
    "nrDomu": 104,
    "ulica": "Schroeders Avenue",
    "kod": "58-412",
    "miasto": "Glendale",
    "dataUrodzenia": "3.12.1954",
    "miejsceUrodzenia": "Ventress",
    "PESEL": 10052920087,
    "NIP": 9364889426,
    "imieOjca": "Gay",
    "imieMatki": "Shaw",
    "plec": "male",
    "nazwiskoMatki": "Larson",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzX",
    "nrDokumentu": "XYZ833761",
    "email": "shawlarson@crustatia.com",
    "telefon": "(969) 480-3099",
    "wyksztalcenie": "gimnazjalne",
    "obywatelstwo": "niemieckie",
    "narodowosc": "India"
  },
  {
    "imie": "Mercedes",
    "nazwisko": "Barrera",
    "nazwiskoRodowe": "Gonzales",
    "nrDomu": 169,
    "ulica": "Sedgwick Place",
    "kod": "21-777",
    "miasto": "Bellfountain",
    "dataUrodzenia": "15.2.1943",
    "miejsceUrodzenia": "Guilford",
    "PESEL": 64022631048,
    "NIP": 6337688035,
    "imieOjca": "Patton",
    "imieMatki": "Ines",
    "plec": "female",
    "nazwiskoMatki": "Odom",
    "rodzajDokumentuTozsamosci": "paszport",
    "wydanyPrzez": "BurmistrzZ",
    "nrDokumentu": "XYZ800583",
    "email": "inesodom@crustatia.com",
    "telefon": "(919) 466-3108",
    "wyksztalcenie": "gimnazjalne",
    "obywatelstwo": "niemieckie",
    "narodowosc": "Burundi"
  },
  {
    "imie": "Hammond",
    "nazwisko": "Riddle",
    "nazwiskoRodowe": "Oliver",
    "nrDomu": 61,
    "ulica": "Eaton Court",
    "kod": "47-130",
    "miasto": "Sanders",
    "dataUrodzenia": "12.10.1909",
    "miejsceUrodzenia": "Bainbridge",
    "PESEL": 69091664024,
    "NIP": 7792673354,
    "imieOjca": "Bishop",
    "imieMatki": "Tisha",
    "plec": "female",
    "nazwiskoMatki": "Lambert",
    "rodzajDokumentuTozsamosci": "paszport",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ661525",
    "email": "tishalambert@crustatia.com",
    "telefon": "(890) 459-2573",
    "wyksztalcenie": "gimnazjalne",
    "obywatelstwo": "polskie",
    "narodowosc": "United States"
  },
  {
    "imie": "Madeleine",
    "nazwisko": "Cobb",
    "nazwiskoRodowe": "Welch",
    "nrDomu": 28,
    "ulica": "Dinsmore Place",
    "kod": "17-397",
    "miasto": "Deseret",
    "dataUrodzenia": "9.9.1984",
    "miejsceUrodzenia": "Weedville",
    "PESEL": 10012134591,
    "NIP": 7250076985,
    "imieOjca": "Hooper",
    "imieMatki": "Brigitte",
    "plec": "female",
    "nazwiskoMatki": "Haynes",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ220895",
    "email": "brigittehaynes@crustatia.com",
    "telefon": "(849) 430-2324",
    "wyksztalcenie": "zasadnicze zawodowe",
    "obywatelstwo": "polskie",
    "narodowosc": "Lesotho"
  },
  {
    "imie": "Ada",
    "nazwisko": "Perkins",
    "nazwiskoRodowe": "Mcclain",
    "nrDomu": 135,
    "ulica": "Monroe Street",
    "kod": "75-616",
    "miasto": "Cliff",
    "dataUrodzenia": "9.1.1908",
    "miejsceUrodzenia": "Nicholson",
    "PESEL": 55031387229,
    "NIP": 7479748121,
    "imieOjca": "Doris",
    "imieMatki": "Lynch",
    "plec": "male",
    "nazwiskoMatki": "Ochoa",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzZ",
    "nrDokumentu": "XYZ973911",
    "email": "lynchochoa@crustatia.com",
    "telefon": "(871) 533-3980",
    "wyksztalcenie": "podstawowe",
    "obywatelstwo": "polskie",
    "narodowosc": "Gambia"
  },
  {
    "imie": "Rutledge",
    "nazwisko": "Maynard",
    "nazwiskoRodowe": "Becker",
    "nrDomu": 90,
    "ulica": "Thames Street",
    "kod": "28-151",
    "miasto": "Garnet",
    "dataUrodzenia": "5.11.1919",
    "miejsceUrodzenia": "Kipp",
    "PESEL": 44011111216,
    "NIP": 1145732940,
    "imieOjca": "Mia",
    "imieMatki": "Lesa",
    "plec": "female",
    "nazwiskoMatki": "Nixon",
    "rodzajDokumentuTozsamosci": "dowod osobisty",
    "wydanyPrzez": "BurmistrzZ",
    "nrDokumentu": "XYZ276429",
    "email": "lesanixon@crustatia.com",
    "telefon": "(915) 557-2790",
    "wyksztalcenie": "gimnazjalne",
    "obywatelstwo": "niemieckie",
    "narodowosc": "Trinidad and Tobago"
  },
  {
    "imie": "Phyllis",
    "nazwisko": "Espinoza",
    "nazwiskoRodowe": "Keith",
    "nrDomu": 164,
    "ulica": "Bergen Avenue",
    "kod": "96-717",
    "miasto": "Stewart",
    "dataUrodzenia": "8.2.2009",
    "miejsceUrodzenia": "Springhill",
    "PESEL": 15032074116,
    "NIP": 9388658797,
    "imieOjca": "Raymond",
    "imieMatki": "Lancaster",
    "plec": "male",
    "nazwiskoMatki": "Daugherty",
    "rodzajDokumentuTozsamosci": "dowod osobisty",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ657353",
    "email": "lancasterdaugherty@crustatia.com",
    "telefon": "(813) 508-3940",
    "wyksztalcenie": "gimnazjalne",
    "obywatelstwo": "francuskie",
    "narodowosc": "Bolivia"
  },
  {
    "imie": "Clay",
    "nazwisko": "Conley",
    "nazwiskoRodowe": "Henson",
    "nrDomu": 166,
    "ulica": "Gotham Avenue",
    "kod": "23-593",
    "miasto": "Berwind",
    "dataUrodzenia": "22.3.2000",
    "miejsceUrodzenia": "Lund",
    "PESEL": 72062453703,
    "NIP": 4157514052,
    "imieOjca": "Susana",
    "imieMatki": "Bertie",
    "plec": "female",
    "nazwiskoMatki": "Moran",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ147757",
    "email": "bertiemoran@crustatia.com",
    "telefon": "(983) 548-3293",
    "wyksztalcenie": "gimnazjalne",
    "obywatelstwo": "francuskie",
    "narodowosc": "Western Sahara"
  },
  {
    "imie": "Elvira",
    "nazwisko": "Jordan",
    "nazwiskoRodowe": "Stout",
    "nrDomu": 175,
    "ulica": "Gallatin Place",
    "kod": "92-428",
    "miasto": "Cartwright",
    "dataUrodzenia": "20.10.2008",
    "miejsceUrodzenia": "Sultana",
    "PESEL": 21062832816,
    "NIP": 3984526746,
    "imieOjca": "Hope",
    "imieMatki": "Celia",
    "plec": "female",
    "nazwiskoMatki": "Berger",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzX",
    "nrDokumentu": "XYZ449379",
    "email": "celiaberger@crustatia.com",
    "telefon": "(906) 443-3078",
    "wyksztalcenie": "gimnazjalne",
    "obywatelstwo": "francuskie",
    "narodowosc": "Antarctica"
  },
  {
    "imie": "Kelley",
    "nazwisko": "Trevino",
    "nazwiskoRodowe": "Sutton",
    "nrDomu": 90,
    "ulica": "Ridge Boulevard",
    "kod": "76-767",
    "miasto": "Dubois",
    "dataUrodzenia": "13.1.1956",
    "miejsceUrodzenia": "Chaparrito",
    "PESEL": 63091857299,
    "NIP": 2875540075,
    "imieOjca": "Sandy",
    "imieMatki": "Felicia",
    "plec": "female",
    "nazwiskoMatki": "Fields",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ871998",
    "email": "feliciafields@crustatia.com",
    "telefon": "(926) 585-2932",
    "wyksztalcenie": "wyższe",
    "obywatelstwo": "polskie",
    "narodowosc": "France, Metropolitan"
  },
  {
    "imie": "Fay",
    "nazwisko": "Santiago",
    "nazwiskoRodowe": "Dennis",
    "nrDomu": 42,
    "ulica": "Frank Court",
    "kod": "96-400",
    "miasto": "Day",
    "dataUrodzenia": "16.8.1959",
    "miejsceUrodzenia": "Aberdeen",
    "PESEL": 17051043574,
    "NIP": 9171880224,
    "imieOjca": "Sanford",
    "imieMatki": "Suarez",
    "plec": "male",
    "nazwiskoMatki": "Woodard",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzX",
    "nrDokumentu": "XYZ878703",
    "email": "suarezwoodard@crustatia.com",
    "telefon": "(953) 491-3137",
    "wyksztalcenie": "wyższe",
    "obywatelstwo": "niemieckie",
    "narodowosc": "Andorra"
  },
  {
    "imie": "Hendricks",
    "nazwisko": "Grant",
    "nazwiskoRodowe": "Callahan",
    "nrDomu": 103,
    "ulica": "Johnson Street",
    "kod": "87-754",
    "miasto": "Alamo",
    "dataUrodzenia": "16.1.1906",
    "miejsceUrodzenia": "Ona",
    "PESEL": 58062189815,
    "NIP": 8576273267,
    "imieOjca": "Erna",
    "imieMatki": "Daugherty",
    "plec": "male",
    "nazwiskoMatki": "Lewis",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzZ",
    "nrDokumentu": "XYZ808565",
    "email": "daughertylewis@crustatia.com",
    "telefon": "(808) 480-3191",
    "wyksztalcenie": "podstawowe",
    "obywatelstwo": "polskie",
    "narodowosc": "Taiwan"
  },
  {
    "imie": "Underwood",
    "nazwisko": "Armstrong",
    "nazwiskoRodowe": "Stewart",
    "nrDomu": 90,
    "ulica": "Beaumont Street",
    "kod": "51-899",
    "miasto": "Holcombe",
    "dataUrodzenia": "30.10.1966",
    "miejsceUrodzenia": "Brooktrails",
    "PESEL": 59092059652,
    "NIP": 3822287637,
    "imieOjca": "Whitney",
    "imieMatki": "Denise",
    "plec": "female",
    "nazwiskoMatki": "Stark",
    "rodzajDokumentuTozsamosci": "dowod osobisty",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ332488",
    "email": "denisestark@crustatia.com",
    "telefon": "(800) 580-2686",
    "wyksztalcenie": "wyższe",
    "obywatelstwo": "francuskie",
    "narodowosc": "Botswana"
  },
  {
    "imie": "Hahn",
    "nazwisko": "Stephenson",
    "nazwiskoRodowe": "Jefferson",
    "nrDomu": 156,
    "ulica": "Allen Avenue",
    "kod": "18-496",
    "miasto": "Williston",
    "dataUrodzenia": "16.7.1903",
    "miejsceUrodzenia": "Belfair",
    "PESEL": 89062552344,
    "NIP": 2006486710,
    "imieOjca": "Mann",
    "imieMatki": "Koch",
    "plec": "male",
    "nazwiskoMatki": "Sloan",
    "rodzajDokumentuTozsamosci": "paszport",
    "wydanyPrzez": "BurmistrzZ",
    "nrDokumentu": "XYZ935752",
    "email": "kochsloan@crustatia.com",
    "telefon": "(929) 559-3049",
    "wyksztalcenie": "podstawowe",
    "obywatelstwo": "francuskie",
    "narodowosc": "Guam"
  },
  {
    "imie": "Toni",
    "nazwisko": "Michael",
    "nazwiskoRodowe": "Hensley",
    "nrDomu": 14,
    "ulica": "Cozine Avenue",
    "kod": "78-616",
    "miasto": "Elizaville",
    "dataUrodzenia": "21.12.1999",
    "miejsceUrodzenia": "Belmont",
    "PESEL": 47041895282,
    "NIP": 4639175989,
    "imieOjca": "Bernice",
    "imieMatki": "Riddle",
    "plec": "male",
    "nazwiskoMatki": "Vazquez",
    "rodzajDokumentuTozsamosci": "paszport",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ642408",
    "email": "riddlevazquez@crustatia.com",
    "telefon": "(916) 488-2386",
    "wyksztalcenie": "gimnazjalne",
    "obywatelstwo": "polskie",
    "narodowosc": "Kazakhstan"
  },
  {
    "imie": "Sharon",
    "nazwisko": "Bright",
    "nazwiskoRodowe": "Winters",
    "nrDomu": 9,
    "ulica": "Trucklemans Lane",
    "kod": "56-638",
    "miasto": "Vandiver",
    "dataUrodzenia": "2.5.1913",
    "miejsceUrodzenia": "Waverly",
    "PESEL": 41062531733,
    "NIP": 3006106547,
    "imieOjca": "Baird",
    "imieMatki": "Valarie",
    "plec": "female",
    "nazwiskoMatki": "Hampton",
    "rodzajDokumentuTozsamosci": "dowod osobisty",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ596050",
    "email": "valariehampton@crustatia.com",
    "telefon": "(983) 581-3321",
    "wyksztalcenie": "gimnazjalne",
    "obywatelstwo": "francuskie",
    "narodowosc": "Bahamas"
  },
  {
    "imie": "Amy",
    "nazwisko": "Beck",
    "nazwiskoRodowe": "Carroll",
    "nrDomu": 23,
    "ulica": "Polar Street",
    "kod": "16-421",
    "miasto": "Baker",
    "dataUrodzenia": "5.4.1944",
    "miejsceUrodzenia": "Chicopee",
    "PESEL": 94071293161,
    "NIP": 1884017262,
    "imieOjca": "Sanchez",
    "imieMatki": "Esperanza",
    "plec": "female",
    "nazwiskoMatki": "Gay",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ430215",
    "email": "esperanzagay@crustatia.com",
    "telefon": "(927) 580-3845",
    "wyksztalcenie": "zasadnicze zawodowe",
    "obywatelstwo": "francuskie",
    "narodowosc": "Sao Tome and Principe"
  },
  {
    "imie": "Sadie",
    "nazwisko": "Mack",
    "nazwiskoRodowe": "Walters",
    "nrDomu": 53,
    "ulica": "Ridgecrest Terrace",
    "kod": "33-772",
    "miasto": "Enoree",
    "dataUrodzenia": "29.1.1903",
    "miejsceUrodzenia": "Dahlen",
    "PESEL": 63021996481,
    "NIP": 6750113140,
    "imieOjca": "Dejesus",
    "imieMatki": "Tasha",
    "plec": "female",
    "nazwiskoMatki": "Torres",
    "rodzajDokumentuTozsamosci": "dowod osobisty",
    "wydanyPrzez": "BurmistrzZ",
    "nrDokumentu": "XYZ637401",
    "email": "tashatorres@crustatia.com",
    "telefon": "(809) 550-3629",
    "wyksztalcenie": "średnie",
    "obywatelstwo": "niemieckie",
    "narodowosc": "French Polynesia"
  },
  {
    "imie": "Garrett",
    "nazwisko": "Holt",
    "nazwiskoRodowe": "Cain",
    "nrDomu": 192,
    "ulica": "President Street",
    "kod": "90-614",
    "miasto": "Fivepointville",
    "dataUrodzenia": "20.11.1963",
    "miejsceUrodzenia": "Cedarville",
    "PESEL": 84041666642,
    "NIP": 8540290905,
    "imieOjca": "Amparo",
    "imieMatki": "Jewell",
    "plec": "female",
    "nazwiskoMatki": "Horn",
    "rodzajDokumentuTozsamosci": "paszport",
    "wydanyPrzez": "BurmistrzZ",
    "nrDokumentu": "XYZ751763",
    "email": "jewellhorn@crustatia.com",
    "telefon": "(921) 405-2670",
    "wyksztalcenie": "gimnazjalne",
    "obywatelstwo": "niemieckie",
    "narodowosc": "Seychelles"
  },
  {
    "imie": "Nicholson",
    "nazwisko": "Snow",
    "nazwiskoRodowe": "Mcpherson",
    "nrDomu": 175,
    "ulica": "River Street",
    "kod": "93-357",
    "miasto": "Carrizo",
    "dataUrodzenia": "17.9.1902",
    "miejsceUrodzenia": "Clinton",
    "PESEL": 47062568092,
    "NIP": 2962846674,
    "imieOjca": "Cote",
    "imieMatki": "Hunt",
    "plec": "male",
    "nazwiskoMatki": "Steele",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzZ",
    "nrDokumentu": "XYZ167836",
    "email": "huntsteele@crustatia.com",
    "telefon": "(960) 426-3479",
    "wyksztalcenie": "wyższe",
    "obywatelstwo": "francuskie",
    "narodowosc": "Morocco"
  },
  {
    "imie": "Margaret",
    "nazwisko": "Bishop",
    "nazwiskoRodowe": "Velez",
    "nrDomu": 82,
    "ulica": "Ditmars Street",
    "kod": "56-109",
    "miasto": "Kenmar",
    "dataUrodzenia": "17.11.1934",
    "miejsceUrodzenia": "Wyano",
    "PESEL": 23081442036,
    "NIP": 6145293813,
    "imieOjca": "Marie",
    "imieMatki": "Ashley",
    "plec": "male",
    "nazwiskoMatki": "Cole",
    "rodzajDokumentuTozsamosci": "dowod osobisty",
    "wydanyPrzez": "BurmistrzX",
    "nrDokumentu": "XYZ873450",
    "email": "ashleycole@crustatia.com",
    "telefon": "(891) 540-2201",
    "wyksztalcenie": "zasadnicze zawodowe",
    "obywatelstwo": "francuskie",
    "narodowosc": "French Guiana"
  },
  {
    "imie": "Marisa",
    "nazwisko": "Rivera",
    "nazwiskoRodowe": "Watson",
    "nrDomu": 188,
    "ulica": "Havens Place",
    "kod": "89-722",
    "miasto": "Ada",
    "dataUrodzenia": "22.12.1959",
    "miejsceUrodzenia": "Sexton",
    "PESEL": 64011464042,
    "NIP": 1756126017,
    "imieOjca": "Castaneda",
    "imieMatki": "Mercado",
    "plec": "male",
    "nazwiskoMatki": "Dillard",
    "rodzajDokumentuTozsamosci": "dowod osobisty",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ240857",
    "email": "mercadodillard@crustatia.com",
    "telefon": "(994) 457-2420",
    "wyksztalcenie": "gimnazjalne",
    "obywatelstwo": "niemieckie",
    "narodowosc": "Slovenia"
  },
  {
    "imie": "Kaitlin",
    "nazwisko": "Hughes",
    "nazwiskoRodowe": "Whitney",
    "nrDomu": 171,
    "ulica": "Seigel Street",
    "kod": "43-145",
    "miasto": "Valle",
    "dataUrodzenia": "19.9.1909",
    "miejsceUrodzenia": "Singer",
    "PESEL": 42022320447,
    "NIP": 9111285796,
    "imieOjca": "Roth",
    "imieMatki": "Knox",
    "plec": "male",
    "nazwiskoMatki": "Buckley",
    "rodzajDokumentuTozsamosci": "dowod osobisty",
    "wydanyPrzez": "BurmistrzX",
    "nrDokumentu": "XYZ614997",
    "email": "knoxbuckley@crustatia.com",
    "telefon": "(937) 519-3967",
    "wyksztalcenie": "podstawowe",
    "obywatelstwo": "niemieckie",
    "narodowosc": "Belize"
  },
  {
    "imie": "Janell",
    "nazwisko": "Blackburn",
    "nazwiskoRodowe": "Campos",
    "nrDomu": 103,
    "ulica": "Macdougal Street",
    "kod": "94-856",
    "miasto": "Morriston",
    "dataUrodzenia": "25.8.1931",
    "miejsceUrodzenia": "Bedias",
    "PESEL": 63031276158,
    "NIP": 4176583847,
    "imieOjca": "Joyce",
    "imieMatki": "Christine",
    "plec": "female",
    "nazwiskoMatki": "Simmons",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzX",
    "nrDokumentu": "XYZ603087",
    "email": "christinesimmons@crustatia.com",
    "telefon": "(957) 535-3135",
    "wyksztalcenie": "wyższe",
    "obywatelstwo": "polskie",
    "narodowosc": "Peru"
  },
  {
    "imie": "Ortiz",
    "nazwisko": "Holder",
    "nazwiskoRodowe": "Garza",
    "nrDomu": 130,
    "ulica": "Waldorf Court",
    "kod": "53-112",
    "miasto": "Trail",
    "dataUrodzenia": "27.12.1933",
    "miejsceUrodzenia": "Tecolotito",
    "PESEL": 52062970653,
    "NIP": 9310367785,
    "imieOjca": "Gomez",
    "imieMatki": "Petra",
    "plec": "female",
    "nazwiskoMatki": "Mooney",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzX",
    "nrDokumentu": "XYZ907166",
    "email": "petramooney@crustatia.com",
    "telefon": "(804) 430-3976",
    "wyksztalcenie": "średnie",
    "obywatelstwo": "niemieckie",
    "narodowosc": "Togo"
  },
  {
    "imie": "Ashlee",
    "nazwisko": "Carter",
    "nazwiskoRodowe": "Page",
    "nrDomu": 105,
    "ulica": "Nichols Avenue",
    "kod": "61-485",
    "miasto": "Fruitdale",
    "dataUrodzenia": "19.4.1921",
    "miejsceUrodzenia": "Shaft",
    "PESEL": 51053012969,
    "NIP": 4358568331,
    "imieOjca": "Valencia",
    "imieMatki": "Ola",
    "plec": "female",
    "nazwiskoMatki": "Pickett",
    "rodzajDokumentuTozsamosci": "dowod osobisty",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ833586",
    "email": "olapickett@crustatia.com",
    "telefon": "(831) 498-2940",
    "wyksztalcenie": "gimnazjalne",
    "obywatelstwo": "niemieckie",
    "narodowosc": "Liberia"
  },
  {
    "imie": "Shelly",
    "nazwisko": "King",
    "nazwiskoRodowe": "Ellis",
    "nrDomu": 164,
    "ulica": "Pine Street",
    "kod": "15-909",
    "miasto": "Joes",
    "dataUrodzenia": "25.3.1987",
    "miejsceUrodzenia": "Darrtown",
    "PESEL": 84061487670,
    "NIP": 8800197248,
    "imieOjca": "Harriett",
    "imieMatki": "Sally",
    "plec": "female",
    "nazwiskoMatki": "Herman",
    "rodzajDokumentuTozsamosci": "dowod osobisty",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ338507",
    "email": "sallyherman@crustatia.com",
    "telefon": "(975) 451-3059",
    "wyksztalcenie": "podstawowe",
    "obywatelstwo": "niemieckie",
    "narodowosc": "Mongolia"
  },
  {
    "imie": "Carney",
    "nazwisko": "Barrett",
    "nazwiskoRodowe": "Singleton",
    "nrDomu": 95,
    "ulica": "Church Avenue",
    "kod": "74-747",
    "miasto": "Malott",
    "dataUrodzenia": "4.9.1945",
    "miejsceUrodzenia": "Caroline",
    "PESEL": 54042620246,
    "NIP": 9801313861,
    "imieOjca": "Bentley",
    "imieMatki": "Holly",
    "plec": "female",
    "nazwiskoMatki": "Curtis",
    "rodzajDokumentuTozsamosci": "dowod osobisty",
    "wydanyPrzez": "BurmistrzZ",
    "nrDokumentu": "XYZ338283",
    "email": "hollycurtis@crustatia.com",
    "telefon": "(986) 497-3435",
    "wyksztalcenie": "średnie",
    "obywatelstwo": "polskie",
    "narodowosc": "Iceland"
  },
  {
    "imie": "Alberta",
    "nazwisko": "Reed",
    "nazwiskoRodowe": "Cervantes",
    "nrDomu": 135,
    "ulica": "Estate Road",
    "kod": "40-783",
    "miasto": "Walker",
    "dataUrodzenia": "25.8.1906",
    "miejsceUrodzenia": "Churchill",
    "PESEL": 30072737697,
    "NIP": 2692355635,
    "imieOjca": "Lee",
    "imieMatki": "Solomon",
    "plec": "male",
    "nazwiskoMatki": "Mckee",
    "rodzajDokumentuTozsamosci": "dowod osobisty",
    "wydanyPrzez": "BurmistrzZ",
    "nrDokumentu": "XYZ141736",
    "email": "solomonmckee@crustatia.com",
    "telefon": "(835) 481-2449",
    "wyksztalcenie": "zasadnicze zawodowe",
    "obywatelstwo": "polskie",
    "narodowosc": "Northern Mariana Islands"
  },
  {
    "imie": "Hatfield",
    "nazwisko": "Richard",
    "nazwiskoRodowe": "Kelly",
    "nrDomu": 198,
    "ulica": "King Street",
    "kod": "94-582",
    "miasto": "Witmer",
    "dataUrodzenia": "6.5.1946",
    "miejsceUrodzenia": "Hartsville/Hartley",
    "PESEL": 85022526886,
    "NIP": 7517005433,
    "imieOjca": "Knight",
    "imieMatki": "Tyson",
    "plec": "male",
    "nazwiskoMatki": "Shaffer",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzX",
    "nrDokumentu": "XYZ998036",
    "email": "tysonshaffer@crustatia.com",
    "telefon": "(879) 594-2382",
    "wyksztalcenie": "wyższe",
    "obywatelstwo": "francuskie",
    "narodowosc": "Rwanda"
  },
  {
    "imie": "Reese",
    "nazwisko": "Hendrix",
    "nazwiskoRodowe": "Nicholson",
    "nrDomu": 129,
    "ulica": "Jackson Place",
    "kod": "12-922",
    "miasto": "Dunbar",
    "dataUrodzenia": "26.8.1958",
    "miejsceUrodzenia": "Adelino",
    "PESEL": 79072034629,
    "NIP": 6735915908,
    "imieOjca": "Elsie",
    "imieMatki": "Janice",
    "plec": "female",
    "nazwiskoMatki": "Humphrey",
    "rodzajDokumentuTozsamosci": "dowod osobisty",
    "wydanyPrzez": "BurmistrzZ",
    "nrDokumentu": "XYZ330139",
    "email": "janicehumphrey@crustatia.com",
    "telefon": "(861) 429-2714",
    "wyksztalcenie": "podstawowe",
    "obywatelstwo": "niemieckie",
    "narodowosc": "Azerbaijan"
  },
  {
    "imie": "Mari",
    "nazwisko": "Lowery",
    "nazwiskoRodowe": "Duncan",
    "nrDomu": 38,
    "ulica": "Norfolk Street",
    "kod": "69-112",
    "miasto": "Keller",
    "dataUrodzenia": "21.2.1997",
    "miejsceUrodzenia": "Denio",
    "PESEL": 50091286572,
    "NIP": 4323717231,
    "imieOjca": "Ingrid",
    "imieMatki": "Nora",
    "plec": "female",
    "nazwiskoMatki": "Sargent",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ808014",
    "email": "norasargent@crustatia.com",
    "telefon": "(801) 450-3454",
    "wyksztalcenie": "wyższe",
    "obywatelstwo": "francuskie",
    "narodowosc": "Suriname"
  },
  {
    "imie": "Ethel",
    "nazwisko": "Avila",
    "nazwiskoRodowe": "Garner",
    "nrDomu": 95,
    "ulica": "Gerald Court",
    "kod": "81-958",
    "miasto": "Hendersonville",
    "dataUrodzenia": "25.11.1966",
    "miejsceUrodzenia": "Chelsea",
    "PESEL": 41081248010,
    "NIP": 2996724472,
    "imieOjca": "Blanche",
    "imieMatki": "Oliver",
    "plec": "male",
    "nazwiskoMatki": "Burns",
    "rodzajDokumentuTozsamosci": "dowod osobisty",
    "wydanyPrzez": "BurmistrzX",
    "nrDokumentu": "XYZ484895",
    "email": "oliverburns@crustatia.com",
    "telefon": "(996) 571-3513",
    "wyksztalcenie": "podstawowe",
    "obywatelstwo": "polskie",
    "narodowosc": "Wallis and Futuna Islands"
  },
  {
    "imie": "Michael",
    "nazwisko": "Shepard",
    "nazwiskoRodowe": "Mcbride",
    "nrDomu": 26,
    "ulica": "Irving Place",
    "kod": "10-984",
    "miasto": "Kohatk",
    "dataUrodzenia": "4.5.1995",
    "miejsceUrodzenia": "Davenport",
    "PESEL": 53011960769,
    "NIP": 3920577613,
    "imieOjca": "Paige",
    "imieMatki": "Stefanie",
    "plec": "female",
    "nazwiskoMatki": "Mann",
    "rodzajDokumentuTozsamosci": "paszport",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ959162",
    "email": "stefaniemann@crustatia.com",
    "telefon": "(995) 466-3016",
    "wyksztalcenie": "podstawowe",
    "obywatelstwo": "francuskie",
    "narodowosc": "Korea (South)"
  },
  {
    "imie": "Holmes",
    "nazwisko": "Hayes",
    "nazwiskoRodowe": "Anthony",
    "nrDomu": 113,
    "ulica": "Madeline Court",
    "kod": "88-230",
    "miasto": "Harleigh",
    "dataUrodzenia": "3.10.2010",
    "miejsceUrodzenia": "Ezel",
    "PESEL": 13051743361,
    "NIP": 2967801892,
    "imieOjca": "Tamera",
    "imieMatki": "Brewer",
    "plec": "male",
    "nazwiskoMatki": "Mclaughlin",
    "rodzajDokumentuTozsamosci": "paszport",
    "wydanyPrzez": "BurmistrzZ",
    "nrDokumentu": "XYZ446489",
    "email": "brewermclaughlin@crustatia.com",
    "telefon": "(820) 594-3472",
    "wyksztalcenie": "podstawowe",
    "obywatelstwo": "polskie",
    "narodowosc": "Mauritius"
  },
  {
    "imie": "Flynn",
    "nazwisko": "Bryan",
    "nazwiskoRodowe": "Bentley",
    "nrDomu": 186,
    "ulica": "Bartlett Street",
    "kod": "28-657",
    "miasto": "Chumuckla",
    "dataUrodzenia": "23.11.2000",
    "miejsceUrodzenia": "Stockwell",
    "PESEL": 69021218596,
    "NIP": 3344735023,
    "imieOjca": "Dixie",
    "imieMatki": "Magdalena",
    "plec": "female",
    "nazwiskoMatki": "Donovan",
    "rodzajDokumentuTozsamosci": "paszport",
    "wydanyPrzez": "BurmistrzZ",
    "nrDokumentu": "XYZ863990",
    "email": "magdalenadonovan@crustatia.com",
    "telefon": "(933) 507-3430",
    "wyksztalcenie": "średnie",
    "obywatelstwo": "francuskie",
    "narodowosc": "Israel"
  },
  {
    "imie": "Shelley",
    "nazwisko": "Carpenter",
    "nazwiskoRodowe": "Alexander",
    "nrDomu": 165,
    "ulica": "Pooles Lane",
    "kod": "72-864",
    "miasto": "Forestburg",
    "dataUrodzenia": "15.1.1905",
    "miejsceUrodzenia": "Twilight",
    "PESEL": 21031276804,
    "NIP": 8043033857,
    "imieOjca": "Delores",
    "imieMatki": "Katharine",
    "plec": "female",
    "nazwiskoMatki": "Skinner",
    "rodzajDokumentuTozsamosci": "dowod osobisty",
    "wydanyPrzez": "BurmistrzZ",
    "nrDokumentu": "XYZ495341",
    "email": "katharineskinner@crustatia.com",
    "telefon": "(984) 522-2558",
    "wyksztalcenie": "wyższe",
    "obywatelstwo": "francuskie",
    "narodowosc": "Thailand"
  },
  {
    "imie": "Mullen",
    "nazwisko": "Graves",
    "nazwiskoRodowe": "Evans",
    "nrDomu": 19,
    "ulica": "Schaefer Street",
    "kod": "51-533",
    "miasto": "Belleview",
    "dataUrodzenia": "12.8.1939",
    "miejsceUrodzenia": "Wheatfields",
    "PESEL": 14061077371,
    "NIP": 2890787383,
    "imieOjca": "Madelyn",
    "imieMatki": "Witt",
    "plec": "male",
    "nazwiskoMatki": "Guerrero",
    "rodzajDokumentuTozsamosci": "paszport",
    "wydanyPrzez": "BurmistrzZ",
    "nrDokumentu": "XYZ613498",
    "email": "wittguerrero@crustatia.com",
    "telefon": "(810) 414-3565",
    "wyksztalcenie": "zasadnicze zawodowe",
    "obywatelstwo": "niemieckie",
    "narodowosc": "Cuba"
  },
  {
    "imie": "Bond",
    "nazwisko": "Baird",
    "nazwiskoRodowe": "Knight",
    "nrDomu": 196,
    "ulica": "Bath Avenue",
    "kod": "80-255",
    "miasto": "Elbert",
    "dataUrodzenia": "8.9.2005",
    "miejsceUrodzenia": "Westphalia",
    "PESEL": 64011277471,
    "NIP": 2785765877,
    "imieOjca": "Corrine",
    "imieMatki": "Letitia",
    "plec": "female",
    "nazwiskoMatki": "Marks",
    "rodzajDokumentuTozsamosci": "paszport",
    "wydanyPrzez": "BurmistrzX",
    "nrDokumentu": "XYZ134707",
    "email": "letitiamarks@crustatia.com",
    "telefon": "(901) 511-2419",
    "wyksztalcenie": "gimnazjalne",
    "obywatelstwo": "polskie",
    "narodowosc": "Tokelau"
  },
  {
    "imie": "Burke",
    "nazwisko": "Curry",
    "nazwiskoRodowe": "Middleton",
    "nrDomu": 89,
    "ulica": "Thornton Street",
    "kod": "70-883",
    "miasto": "Roulette",
    "dataUrodzenia": "13.4.2011",
    "miejsceUrodzenia": "Lafferty",
    "PESEL": 83052885488,
    "NIP": 9247785000,
    "imieOjca": "Wall",
    "imieMatki": "Enid",
    "plec": "female",
    "nazwiskoMatki": "Stanley",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ944484",
    "email": "enidstanley@crustatia.com",
    "telefon": "(942) 573-2582",
    "wyksztalcenie": "wyższe",
    "obywatelstwo": "polskie",
    "narodowosc": "Japan"
  },
  {
    "imie": "Washington",
    "nazwisko": "Davidson",
    "nazwiskoRodowe": "Jacobson",
    "nrDomu": 179,
    "ulica": "Glen Street",
    "kod": "88-614",
    "miasto": "Genoa",
    "dataUrodzenia": "17.11.1962",
    "miejsceUrodzenia": "Conestoga",
    "PESEL": 59072535422,
    "NIP": 9078573367,
    "imieOjca": "Greta",
    "imieMatki": "Britt",
    "plec": "male",
    "nazwiskoMatki": "Fry",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ455045",
    "email": "brittfry@crustatia.com",
    "telefon": "(921) 506-2604",
    "wyksztalcenie": "wyższe",
    "obywatelstwo": "niemieckie",
    "narodowosc": "Mauritania"
  },
  {
    "imie": "Rachel",
    "nazwisko": "Chase",
    "nazwiskoRodowe": "Miles",
    "nrDomu": 41,
    "ulica": "Hill Street",
    "kod": "90-287",
    "miasto": "Grahamtown",
    "dataUrodzenia": "6.4.1928",
    "miejsceUrodzenia": "Tioga",
    "PESEL": 36052753245,
    "NIP": 2352656766,
    "imieOjca": "Boyd",
    "imieMatki": "Gena",
    "plec": "female",
    "nazwiskoMatki": "Frost",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzX",
    "nrDokumentu": "XYZ258802",
    "email": "genafrost@crustatia.com",
    "telefon": "(898) 590-2610",
    "wyksztalcenie": "podstawowe",
    "obywatelstwo": "polskie",
    "narodowosc": "Mozambique"
  },
  {
    "imie": "Leanna",
    "nazwisko": "Soto",
    "nazwiskoRodowe": "Nichols",
    "nrDomu": 76,
    "ulica": "Visitation Place",
    "kod": "84-700",
    "miasto": "Ogema",
    "dataUrodzenia": "24.5.2003",
    "miejsceUrodzenia": "Kempton",
    "PESEL": 12012942234,
    "NIP": 9422485514,
    "imieOjca": "Gallegos",
    "imieMatki": "Lisa",
    "plec": "female",
    "nazwiskoMatki": "Melton",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzX",
    "nrDokumentu": "XYZ107488",
    "email": "lisamelton@crustatia.com",
    "telefon": "(960) 554-2003",
    "wyksztalcenie": "zasadnicze zawodowe",
    "obywatelstwo": "niemieckie",
    "narodowosc": "Comoros"
  },
  {
    "imie": "Krystal",
    "nazwisko": "Chan",
    "nazwiskoRodowe": "Greer",
    "nrDomu": 95,
    "ulica": "Florence Avenue",
    "kod": "84-140",
    "miasto": "Morgandale",
    "dataUrodzenia": "20.5.2000",
    "miejsceUrodzenia": "Westwood",
    "PESEL": 36012769955,
    "NIP": 5906956813,
    "imieOjca": "Cunningham",
    "imieMatki": "Vanessa",
    "plec": "female",
    "nazwiskoMatki": "England",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ610051",
    "email": "vanessaengland@crustatia.com",
    "telefon": "(937) 485-2443",
    "wyksztalcenie": "podstawowe",
    "obywatelstwo": "francuskie",
    "narodowosc": "Chad"
  },
  {
    "imie": "Chang",
    "nazwisko": "Sandoval",
    "nazwiskoRodowe": "Gilliam",
    "nrDomu": 19,
    "ulica": "Stockton Street",
    "kod": "91-190",
    "miasto": "Castleton",
    "dataUrodzenia": "2.6.1931",
    "miejsceUrodzenia": "Sims",
    "PESEL": 78062173001,
    "NIP": 7421903130,
    "imieOjca": "Deidre",
    "imieMatki": "Nelson",
    "plec": "male",
    "nazwiskoMatki": "Thornton",
    "rodzajDokumentuTozsamosci": "paszport",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ427958",
    "email": "nelsonthornton@crustatia.com",
    "telefon": "(822) 564-2150",
    "wyksztalcenie": "podstawowe",
    "obywatelstwo": "niemieckie",
    "narodowosc": "Uruguay"
  },
  {
    "imie": "Herminia",
    "nazwisko": "Peck",
    "nazwiskoRodowe": "Sheppard",
    "nrDomu": 139,
    "ulica": "Bancroft Place",
    "kod": "42-273",
    "miasto": "Coalmont",
    "dataUrodzenia": "26.8.1940",
    "miejsceUrodzenia": "Driftwood",
    "PESEL": 67032583496,
    "NIP": 6445900700,
    "imieOjca": "Trisha",
    "imieMatki": "Olivia",
    "plec": "female",
    "nazwiskoMatki": "Willis",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzX",
    "nrDokumentu": "XYZ913376",
    "email": "oliviawillis@crustatia.com",
    "telefon": "(952) 519-2549",
    "wyksztalcenie": "średnie",
    "obywatelstwo": "francuskie",
    "narodowosc": "Cayman Islands"
  },
  {
    "imie": "Farrell",
    "nazwisko": "Campbell",
    "nazwiskoRodowe": "Jacobs",
    "nrDomu": 154,
    "ulica": "Tennis Court",
    "kod": "89-592",
    "miasto": "Rowe",
    "dataUrodzenia": "13.10.1971",
    "miejsceUrodzenia": "Eastvale",
    "PESEL": 71051586315,
    "NIP": 9468179501,
    "imieOjca": "Harvey",
    "imieMatki": "Blair",
    "plec": "male",
    "nazwiskoMatki": "David",
    "rodzajDokumentuTozsamosci": "paszport",
    "wydanyPrzez": "BurmistrzZ",
    "nrDokumentu": "XYZ809044",
    "email": "blairdavid@crustatia.com",
    "telefon": "(944) 409-2826",
    "wyksztalcenie": "średnie",
    "obywatelstwo": "francuskie",
    "narodowosc": "South Africa"
  },
  {
    "imie": "Warren",
    "nazwisko": "Holland",
    "nazwiskoRodowe": "Robinson",
    "nrDomu": 80,
    "ulica": "Louise Terrace",
    "kod": "93-820",
    "miasto": "Edenburg",
    "dataUrodzenia": "16.9.1998",
    "miejsceUrodzenia": "Brambleton",
    "PESEL": 29022146582,
    "NIP": 5569016035,
    "imieOjca": "Susan",
    "imieMatki": "Concetta",
    "plec": "female",
    "nazwiskoMatki": "Walton",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzX",
    "nrDokumentu": "XYZ913275",
    "email": "concettawalton@crustatia.com",
    "telefon": "(864) 599-3076",
    "wyksztalcenie": "podstawowe",
    "obywatelstwo": "francuskie",
    "narodowosc": "Niger"
  },
  {
    "imie": "King",
    "nazwisko": "Hanson",
    "nazwiskoRodowe": "Guy",
    "nrDomu": 142,
    "ulica": "Sackman Street",
    "kod": "52-657",
    "miasto": "Zortman",
    "dataUrodzenia": "1.5.1907",
    "miejsceUrodzenia": "Brutus",
    "PESEL": 65082726972,
    "NIP": 5045418045,
    "imieOjca": "Karyn",
    "imieMatki": "Alejandra",
    "plec": "female",
    "nazwiskoMatki": "Morris",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzX",
    "nrDokumentu": "XYZ800240",
    "email": "alejandramorris@crustatia.com",
    "telefon": "(952) 514-2058",
    "wyksztalcenie": "zasadnicze zawodowe",
    "obywatelstwo": "polskie",
    "narodowosc": "United Kingdom"
  },
  {
    "imie": "Melody",
    "nazwisko": "Rollins",
    "nazwiskoRodowe": "Molina",
    "nrDomu": 30,
    "ulica": "Bleecker Street",
    "kod": "35-309",
    "miasto": "Calvary",
    "dataUrodzenia": "3.12.2005",
    "miejsceUrodzenia": "Sheatown",
    "PESEL": 92052243293,
    "NIP": 2813248739,
    "imieOjca": "Sharp",
    "imieMatki": "Keisha",
    "plec": "female",
    "nazwiskoMatki": "Lara",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzX",
    "nrDokumentu": "XYZ735120",
    "email": "keishalara@crustatia.com",
    "telefon": "(863) 402-3847",
    "wyksztalcenie": "średnie",
    "obywatelstwo": "polskie",
    "narodowosc": "Cameroon"
  },
  {
    "imie": "Ronda",
    "nazwisko": "Morrow",
    "nazwiskoRodowe": "Woods",
    "nrDomu": 2,
    "ulica": "Strong Place",
    "kod": "20-844",
    "miasto": "Clayville",
    "dataUrodzenia": "1.12.1940",
    "miejsceUrodzenia": "Tivoli",
    "PESEL": 60012273924,
    "NIP": 7735276465,
    "imieOjca": "Greer",
    "imieMatki": "Gabriela",
    "plec": "female",
    "nazwiskoMatki": "Ortiz",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzX",
    "nrDokumentu": "XYZ378270",
    "email": "gabrielaortiz@crustatia.com",
    "telefon": "(900) 526-2609",
    "wyksztalcenie": "gimnazjalne",
    "obywatelstwo": "francuskie",
    "narodowosc": "Denmark"
  },
  {
    "imie": "Alisha",
    "nazwisko": "Bolton",
    "nazwiskoRodowe": "Shields",
    "nrDomu": 48,
    "ulica": "Williams Avenue",
    "kod": "97-887",
    "miasto": "Darbydale",
    "dataUrodzenia": "18.5.1913",
    "miejsceUrodzenia": "Silkworth",
    "PESEL": 89061969283,
    "NIP": 9218559605,
    "imieOjca": "Richardson",
    "imieMatki": "Willa",
    "plec": "female",
    "nazwiskoMatki": "Townsend",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzX",
    "nrDokumentu": "XYZ266013",
    "email": "willatownsend@crustatia.com",
    "telefon": "(900) 402-3696",
    "wyksztalcenie": "podstawowe",
    "obywatelstwo": "francuskie",
    "narodowosc": "Brazil"
  },
  {
    "imie": "Cleveland",
    "nazwisko": "Weeks",
    "nazwiskoRodowe": "Clayton",
    "nrDomu": 88,
    "ulica": "Kingston Avenue",
    "kod": "18-459",
    "miasto": "Whitehaven",
    "dataUrodzenia": "7.7.1973",
    "miejsceUrodzenia": "Stockdale",
    "PESEL": 31021444491,
    "NIP": 5797139290,
    "imieOjca": "Nicole",
    "imieMatki": "Erma",
    "plec": "female",
    "nazwiskoMatki": "Turner",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ177108",
    "email": "ermaturner@crustatia.com",
    "telefon": "(835) 510-2327",
    "wyksztalcenie": "średnie",
    "obywatelstwo": "niemieckie",
    "narodowosc": "Uganda"
  },
  {
    "imie": "Dora",
    "nazwisko": "Martinez",
    "nazwiskoRodowe": "Osborn",
    "nrDomu": 150,
    "ulica": "Delmonico Place",
    "kod": "65-680",
    "miasto": "Cashtown",
    "dataUrodzenia": "9.4.1969",
    "miejsceUrodzenia": "Coultervillle",
    "PESEL": 82032834235,
    "NIP": 3486010927,
    "imieOjca": "Karin",
    "imieMatki": "Luna",
    "plec": "male",
    "nazwiskoMatki": "Shaw",
    "rodzajDokumentuTozsamosci": "paszport",
    "wydanyPrzez": "BurmistrzX",
    "nrDokumentu": "XYZ867311",
    "email": "lunashaw@crustatia.com",
    "telefon": "(963) 498-3317",
    "wyksztalcenie": "zasadnicze zawodowe",
    "obywatelstwo": "polskie",
    "narodowosc": "Algeria"
  },
  {
    "imie": "Rosales",
    "nazwisko": "Bonner",
    "nazwiskoRodowe": "Navarro",
    "nrDomu": 138,
    "ulica": "Stewart Street",
    "kod": "18-195",
    "miasto": "Edinburg",
    "dataUrodzenia": "1.2.1978",
    "miejsceUrodzenia": "Brazos",
    "PESEL": 72071167360,
    "NIP": 1466463288,
    "imieOjca": "Patty",
    "imieMatki": "Meadows",
    "plec": "male",
    "nazwiskoMatki": "Estes",
    "rodzajDokumentuTozsamosci": "paszport",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ262797",
    "email": "meadowsestes@crustatia.com",
    "telefon": "(875) 564-3981",
    "wyksztalcenie": "zasadnicze zawodowe",
    "obywatelstwo": "francuskie",
    "narodowosc": "Korea (North)"
  },
  {
    "imie": "Becky",
    "nazwisko": "Morton",
    "nazwiskoRodowe": "Hess",
    "nrDomu": 170,
    "ulica": "Alabama Avenue",
    "kod": "60-870",
    "miasto": "Needmore",
    "dataUrodzenia": "30.1.1963",
    "miejsceUrodzenia": "Boomer",
    "PESEL": 11072847479,
    "NIP": 3034933308,
    "imieOjca": "Adrienne",
    "imieMatki": "Alicia",
    "plec": "female",
    "nazwiskoMatki": "Weaver",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzX",
    "nrDokumentu": "XYZ496988",
    "email": "aliciaweaver@crustatia.com",
    "telefon": "(862) 417-2482",
    "wyksztalcenie": "wyższe",
    "obywatelstwo": "polskie",
    "narodowosc": "Gibraltar"
  },
  {
    "imie": "Holloway",
    "nazwisko": "Lindsay",
    "nazwiskoRodowe": "Burke",
    "nrDomu": 67,
    "ulica": "Laurel Avenue",
    "kod": "28-554",
    "miasto": "Cumberland",
    "dataUrodzenia": "12.2.1957",
    "miejsceUrodzenia": "Wescosville",
    "PESEL": 33061684067,
    "NIP": 3956944697,
    "imieOjca": "Ward",
    "imieMatki": "Sophie",
    "plec": "female",
    "nazwiskoMatki": "Erickson",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ521492",
    "email": "sophieerickson@crustatia.com",
    "telefon": "(974) 463-2860",
    "wyksztalcenie": "średnie",
    "obywatelstwo": "francuskie",
    "narodowosc": "Eritrea"
  },
  {
    "imie": "Palmer",
    "nazwisko": "Walter",
    "nazwiskoRodowe": "Gould",
    "nrDomu": 200,
    "ulica": "Voorhies Avenue",
    "kod": "38-778",
    "miasto": "Sattley",
    "dataUrodzenia": "23.1.1990",
    "miejsceUrodzenia": "Hessville",
    "PESEL": 63061673446,
    "NIP": 2130391029,
    "imieOjca": "Virginia",
    "imieMatki": "Latonya",
    "plec": "female",
    "nazwiskoMatki": "Justice",
    "rodzajDokumentuTozsamosci": "paszport",
    "wydanyPrzez": "BurmistrzX",
    "nrDokumentu": "XYZ736314",
    "email": "latonyajustice@crustatia.com",
    "telefon": "(946) 540-2236",
    "wyksztalcenie": "wyższe",
    "obywatelstwo": "francuskie",
    "narodowosc": "Saint Vincent and The Grenadines"
  },
  {
    "imie": "Sylvia",
    "nazwisko": "Franklin",
    "nazwiskoRodowe": "Sweet",
    "nrDomu": 49,
    "ulica": "Cove Lane",
    "kod": "61-310",
    "miasto": "Mahtowa",
    "dataUrodzenia": "11.10.1903",
    "miejsceUrodzenia": "Wanship",
    "PESEL": 45022868662,
    "NIP": 5313222949,
    "imieOjca": "Rhodes",
    "imieMatki": "Anita",
    "plec": "female",
    "nazwiskoMatki": "Pope",
    "rodzajDokumentuTozsamosci": "paszport",
    "wydanyPrzez": "BurmistrzX",
    "nrDokumentu": "XYZ912826",
    "email": "anitapope@crustatia.com",
    "telefon": "(896) 455-3148",
    "wyksztalcenie": "średnie",
    "obywatelstwo": "polskie",
    "narodowosc": "Egypt"
  },
  {
    "imie": "Tammy",
    "nazwisko": "Moon",
    "nazwiskoRodowe": "Glover",
    "nrDomu": 20,
    "ulica": "Guernsey Street",
    "kod": "68-659",
    "miasto": "Falconaire",
    "dataUrodzenia": "29.9.1904",
    "miejsceUrodzenia": "Makena",
    "PESEL": 85012670968,
    "NIP": 3790051454,
    "imieOjca": "Vance",
    "imieMatki": "Tamika",
    "plec": "female",
    "nazwiskoMatki": "Mcfarland",
    "rodzajDokumentuTozsamosci": "dowod osobisty",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ833791",
    "email": "tamikamcfarland@crustatia.com",
    "telefon": "(983) 451-2831",
    "wyksztalcenie": "średnie",
    "obywatelstwo": "francuskie",
    "narodowosc": "US Minor Outlying Islands"
  },
  {
    "imie": "Keith",
    "nazwisko": "Burt",
    "nazwiskoRodowe": "Jones",
    "nrDomu": 58,
    "ulica": "Gatling Place",
    "kod": "11-105",
    "miasto": "Linganore",
    "dataUrodzenia": "2.9.1971",
    "miejsceUrodzenia": "Vaughn",
    "PESEL": 53091911078,
    "NIP": 4542499853,
    "imieOjca": "Lizzie",
    "imieMatki": "Goodman",
    "plec": "male",
    "nazwiskoMatki": "Contreras",
    "rodzajDokumentuTozsamosci": "paszport",
    "wydanyPrzez": "BurmistrzZ",
    "nrDokumentu": "XYZ297943",
    "email": "goodmancontreras@crustatia.com",
    "telefon": "(937) 596-2624",
    "wyksztalcenie": "podstawowe",
    "obywatelstwo": "niemieckie",
    "narodowosc": "San Marino"
  },
  {
    "imie": "Vargas",
    "nazwisko": "Gross",
    "nazwiskoRodowe": "Carney",
    "nrDomu": 38,
    "ulica": "Georgia Avenue",
    "kod": "98-853",
    "miasto": "Emory",
    "dataUrodzenia": "20.2.1990",
    "miejsceUrodzenia": "Caln",
    "PESEL": 56092060307,
    "NIP": 4700782039,
    "imieOjca": "Scott",
    "imieMatki": "Manuela",
    "plec": "female",
    "nazwiskoMatki": "Hamilton",
    "rodzajDokumentuTozsamosci": "dowod osobisty",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ182923",
    "email": "manuelahamilton@crustatia.com",
    "telefon": "(905) 511-2240",
    "wyksztalcenie": "podstawowe",
    "obywatelstwo": "niemieckie",
    "narodowosc": "Guadeloupe"
  },
  {
    "imie": "Carlson",
    "nazwisko": "Taylor",
    "nazwiskoRodowe": "Pratt",
    "nrDomu": 144,
    "ulica": "Dorset Street",
    "kod": "32-466",
    "miasto": "Sutton",
    "dataUrodzenia": "11.7.2000",
    "miejsceUrodzenia": "Hampstead",
    "PESEL": 22072390005,
    "NIP": 5000248639,
    "imieOjca": "Edwards",
    "imieMatki": "Foster",
    "plec": "male",
    "nazwiskoMatki": "Juarez",
    "rodzajDokumentuTozsamosci": "paszport",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ640771",
    "email": "fosterjuarez@crustatia.com",
    "telefon": "(905) 464-3602",
    "wyksztalcenie": "wyższe",
    "obywatelstwo": "polskie",
    "narodowosc": "Afghanistan"
  },
  {
    "imie": "Jordan",
    "nazwisko": "Doyle",
    "nazwiskoRodowe": "Leon",
    "nrDomu": 135,
    "ulica": "Radde Place",
    "kod": "85-402",
    "miasto": "Hanover",
    "dataUrodzenia": "23.8.1939",
    "miejsceUrodzenia": "Waumandee",
    "PESEL": 18053077655,
    "NIP": 8473687876,
    "imieOjca": "Leanne",
    "imieMatki": "Neal",
    "plec": "male",
    "nazwiskoMatki": "Hale",
    "rodzajDokumentuTozsamosci": "paszport",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ858295",
    "email": "nealhale@crustatia.com",
    "telefon": "(837) 445-2048",
    "wyksztalcenie": "średnie",
    "obywatelstwo": "polskie",
    "narodowosc": "Tanzania"
  },
  {
    "imie": "Francine",
    "nazwisko": "Griffith",
    "nazwiskoRodowe": "Underwood",
    "nrDomu": 175,
    "ulica": "Vandervoort Avenue",
    "kod": "65-954",
    "miasto": "Fulford",
    "dataUrodzenia": "28.7.1916",
    "miejsceUrodzenia": "Greer",
    "PESEL": 18042162149,
    "NIP": 1683077195,
    "imieOjca": "Bowen",
    "imieMatki": "Serena",
    "plec": "female",
    "nazwiskoMatki": "Irwin",
    "rodzajDokumentuTozsamosci": "paszport",
    "wydanyPrzez": "BurmistrzX",
    "nrDokumentu": "XYZ705282",
    "email": "serenairwin@crustatia.com",
    "telefon": "(993) 503-3978",
    "wyksztalcenie": "wyższe",
    "obywatelstwo": "francuskie",
    "narodowosc": "Nauru"
  },
  {
    "imie": "Sybil",
    "nazwisko": "Franco",
    "nazwiskoRodowe": "Salinas",
    "nrDomu": 139,
    "ulica": "Utica Avenue",
    "kod": "91-819",
    "miasto": "Foxworth",
    "dataUrodzenia": "8.4.1967",
    "miejsceUrodzenia": "Ribera",
    "PESEL": 98051440595,
    "NIP": 8939341661,
    "imieOjca": "Allyson",
    "imieMatki": "Cheryl",
    "plec": "female",
    "nazwiskoMatki": "Reid",
    "rodzajDokumentuTozsamosci": "dowod osobisty",
    "wydanyPrzez": "BurmistrzZ",
    "nrDokumentu": "XYZ601109",
    "email": "cherylreid@crustatia.com",
    "telefon": "(855) 458-2418",
    "wyksztalcenie": "podstawowe",
    "obywatelstwo": "francuskie",
    "narodowosc": "Congo"
  },
  {
    "imie": "Frederick",
    "nazwisko": "Holcomb",
    "nazwiskoRodowe": "Kirkland",
    "nrDomu": 19,
    "ulica": "Chester Avenue",
    "kod": "97-197",
    "miasto": "Snelling",
    "dataUrodzenia": "24.1.1952",
    "miejsceUrodzenia": "Chalfant",
    "PESEL": 92072910093,
    "NIP": 8764088764,
    "imieOjca": "Lesley",
    "imieMatki": "Lawson",
    "plec": "male",
    "nazwiskoMatki": "Spears",
    "rodzajDokumentuTozsamosci": "dowod osobisty",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ819309",
    "email": "lawsonspears@crustatia.com",
    "telefon": "(980) 524-2302",
    "wyksztalcenie": "podstawowe",
    "obywatelstwo": "niemieckie",
    "narodowosc": "Saint Lucia"
  },
  {
    "imie": "Catalina",
    "nazwisko": "Byrd",
    "nazwiskoRodowe": "Hatfield",
    "nrDomu": 184,
    "ulica": "Chauncey Street",
    "kod": "68-706",
    "miasto": "Foscoe",
    "dataUrodzenia": "2.2.1989",
    "miejsceUrodzenia": "Kenwood",
    "PESEL": 17032380219,
    "NIP": 1569175433,
    "imieOjca": "Molly",
    "imieMatki": "Joan",
    "plec": "female",
    "nazwiskoMatki": "Cotton",
    "rodzajDokumentuTozsamosci": "dowod osobisty",
    "wydanyPrzez": "BurmistrzZ",
    "nrDokumentu": "XYZ987457",
    "email": "joancotton@crustatia.com",
    "telefon": "(948) 534-3879",
    "wyksztalcenie": "zasadnicze zawodowe",
    "obywatelstwo": "niemieckie",
    "narodowosc": "Uzbekistan"
  },
  {
    "imie": "Riley",
    "nazwisko": "Kent",
    "nazwiskoRodowe": "Barnes",
    "nrDomu": 82,
    "ulica": "Friel Place",
    "kod": "90-503",
    "miasto": "Beyerville",
    "dataUrodzenia": "25.6.1994",
    "miejsceUrodzenia": "Cucumber",
    "PESEL": 61022161895,
    "NIP": 1273586371,
    "imieOjca": "Hannah",
    "imieMatki": "Rosa",
    "plec": "female",
    "nazwiskoMatki": "Ramsey",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzX",
    "nrDokumentu": "XYZ471447",
    "email": "rosaramsey@crustatia.com",
    "telefon": "(973) 441-2599",
    "wyksztalcenie": "gimnazjalne",
    "obywatelstwo": "polskie",
    "narodowosc": "United Arab Emirates"}]};