var bazaOsob= { osoba:[
  {
    "imie": "Calhoun",
    "nazwisko": "Kelley",
    "nazwiskoRodowe": "Rodriquez",
    "nrDomu": 86,
    "ulica": "Jefferson Street",
    "kod": "18-303",
    "miasto": "Leroy",
    "dataUrodzenia": "10.11.2008",
    "miejsceUrodzenia": "Boykin",
    "PESEL": 97082466119,
    "NIP": 4265024633,
    "imieOjca": "Tiffany",
    "imieMatki": "Parsons",
    "plec": "Pan",
    "nazwiskoMatki": "Holder",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzX",
    "nrDokumentu": "XYZ803605",
    "email": "parsonsholder@nexgene.com",
    "telefon": "(832) 415-2249",
    "wyksztalcenie": "zasadnicze zawodowe",
    "obywatelstwo": "francuskie",
    "narodowosc": "Eritrea"
  },
  {
    "imie": "Le",
    "nazwisko": "Mcintyre",
    "nazwiskoRodowe": "Norman",
    "nrDomu": 197,
    "ulica": "Elm Place",
    "kod": "11-764",
    "miasto": "Retsof",
    "dataUrodzenia": "11.12.1979",
    "miejsceUrodzenia": "Nettie",
    "PESEL": 64021027419,
    "NIP": 8113744710,
    "imieOjca": "Greer",
    "imieMatki": "Norris",
    "plec": "Pan",
    "nazwiskoMatki": "Woodward",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ732394",
    "email": "norriswoodward@nexgene.com",
    "telefon": "(833) 478-3998",
    "wyksztalcenie": "zasadnicze zawodowe",
    "obywatelstwo": "francuskie",
    "narodowosc": "Palau"
  },
  {
    "imie": "Reed",
    "nazwisko": "Fisher",
    "nazwiskoRodowe": "Lang",
    "nrDomu": 67,
    "ulica": "Pershing Loop",
    "kod": "91-249",
    "miasto": "Watrous",
    "dataUrodzenia": "1.10.1993",
    "miejsceUrodzenia": "Cornucopia",
    "PESEL": 21022371833,
    "NIP": 6663971034,
    "imieOjca": "Lillian",
    "imieMatki": "Clarice",
    "plec": "Pani",
    "nazwiskoMatki": "Wolf",
    "rodzajDokumentuTozsamosci": "paszport",
    "wydanyPrzez": "BurmistrzZ",
    "nrDokumentu": "XYZ548127",
    "email": "claricewolf@nexgene.com",
    "telefon": "(946) 433-3812",
    "wyksztalcenie": "zasadnicze zawodowe",
    "obywatelstwo": "francuskie",
    "narodowosc": "Macedonia"
  },
  {
    "imie": "Fay",
    "nazwisko": "Petty",
    "nazwiskoRodowe": "Sheppard",
    "nrDomu": 148,
    "ulica": "Moore Street",
    "kod": "90-826",
    "miasto": "Brethren",
    "dataUrodzenia": "28.11.1996",
    "miejsceUrodzenia": "Connerton",
    "PESEL": 95021061419,
    "NIP": 9581337717,
    "imieOjca": "Best",
    "imieMatki": "Winnie",
    "plec": "Pani",
    "nazwiskoMatki": "Webb",
    "rodzajDokumentuTozsamosci": "dowod osobisty",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ421174",
    "email": "winniewebb@nexgene.com",
    "telefon": "(871) 527-3762",
    "wyksztalcenie": "gimnazjalne",
    "obywatelstwo": "polskie",
    "narodowosc": "Singapore"
  },
  {
    "imie": "Estela",
    "nazwisko": "Bauer",
    "nazwiskoRodowe": "Woodard",
    "nrDomu": 133,
    "ulica": "Chestnut Street",
    "kod": "24-222",
    "miasto": "Statenville",
    "dataUrodzenia": "23.12.1978",
    "miejsceUrodzenia": "Hoagland",
    "PESEL": 39062998040,
    "NIP": 9037316758,
    "imieOjca": "Ramos",
    "imieMatki": "Hallie",
    "plec": "Pan",
    "nazwiskoMatki": "Brock",
    "rodzajDokumentuTozsamosci": "paszport",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ193018",
    "email": "halliebrock@nexgene.com",
    "telefon": "(831) 526-3779",
    "wyksztalcenie": "wyższe",
    "obywatelstwo": "polskie",
    "narodowosc": "Jamaica"
  },
  {
    "imie": "Alejandra",
    "nazwisko": "Dillard",
    "nazwiskoRodowe": "Cohen",
    "nrDomu": 63,
    "ulica": "River Street",
    "kod": "96-165",
    "miasto": "Robinson",
    "dataUrodzenia": "5.12.1974",
    "miejsceUrodzenia": "Camas",
    "PESEL": 57041868748,
    "NIP": 8593573643,
    "imieOjca": "Tami",
    "imieMatki": "Dalton",
    "plec": "Pani",
    "nazwiskoMatki": "Bond",
    "rodzajDokumentuTozsamosci": "dowod osobisty",
    "wydanyPrzez": "BurmistrzX",
    "nrDokumentu": "XYZ241242",
    "email": "daltonbond@nexgene.com",
    "telefon": "(803) 494-2915",
    "wyksztalcenie": "gimnazjalne",
    "obywatelstwo": "francuskie",
    "narodowosc": "Vatican City State (Holy See)"
  },
  {
    "imie": "Reid",
    "nazwisko": "Campos",
    "nazwiskoRodowe": "Mcdonald",
    "nrDomu": 85,
    "ulica": "Beaver Street",
    "kod": "29-595",
    "miasto": "Hannasville",
    "dataUrodzenia": "25.12.1937",
    "miejsceUrodzenia": "Farmers",
    "PESEL": 82082614230,
    "NIP": 3446912693,
    "imieOjca": "Huber",
    "imieMatki": "Hester",
    "plec": "Pan",
    "nazwiskoMatki": "Wise",
    "rodzajDokumentuTozsamosci": "paszport",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ155367",
    "email": "hesterwise@nexgene.com",
    "telefon": "(821) 582-3266",
    "wyksztalcenie": "wyższe",
    "obywatelstwo": "francuskie",
    "narodowosc": "Christmas Island"
  },
  {
    "imie": "Valdez",
    "nazwisko": "Robertson",
    "nazwiskoRodowe": "Langley",
    "nrDomu": 98,
    "ulica": "Anchorage Place",
    "kod": "66-966",
    "miasto": "Trinway",
    "dataUrodzenia": "7.11.1927",
    "miejsceUrodzenia": "Darlington",
    "PESEL": 50032418590,
    "NIP": 5410244803,
    "imieOjca": "Iris",
    "imieMatki": "Weaver",
    "plec": "Pani",
    "nazwiskoMatki": "Marshall",
    "rodzajDokumentuTozsamosci": "paszport",
    "wydanyPrzez": "BurmistrzX",
    "nrDokumentu": "XYZ476116",
    "email": "weavermarshall@nexgene.com",
    "telefon": "(803) 559-3937",
    "wyksztalcenie": "średnie",
    "obywatelstwo": "francuskie",
    "narodowosc": "Turks and Caicos Islands"
  },
  {
    "imie": "Hester",
    "nazwisko": "Shelton",
    "nazwiskoRodowe": "Wynn",
    "nrDomu": 108,
    "ulica": "Lake Street",
    "kod": "98-113",
    "miasto": "Singer",
    "dataUrodzenia": "11.11.1946",
    "miejsceUrodzenia": "Strong",
    "PESEL": 37081215616,
    "NIP": 8097321555,
    "imieOjca": "Lynette",
    "imieMatki": "Deidre",
    "plec": "Pani",
    "nazwiskoMatki": "Abbott",
    "rodzajDokumentuTozsamosci": "paszport",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ254820",
    "email": "deidreabbott@nexgene.com",
    "telefon": "(913) 534-3106",
    "wyksztalcenie": "zasadnicze zawodowe",
    "obywatelstwo": "niemieckie",
    "narodowosc": "United Kingdom"
  },
  {
    "imie": "Hardy",
    "nazwisko": "Sanchez",
    "nazwiskoRodowe": "Mills",
    "nrDomu": 135,
    "ulica": "Williams Court",
    "kod": "18-284",
    "miasto": "Marysville",
    "dataUrodzenia": "17.11.1930",
    "miejsceUrodzenia": "Cassel",
    "PESEL": 97011898122,
    "NIP": 4640694489,
    "imieOjca": "Aisha",
    "imieMatki": "Julianne",
    "plec": "Pani",
    "nazwiskoMatki": "Nixon",
    "rodzajDokumentuTozsamosci": "paszport",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ800012",
    "email": "juliannenixon@nexgene.com",
    "telefon": "(987) 474-3648",
    "wyksztalcenie": "wyższe",
    "obywatelstwo": "francuskie",
    "narodowosc": "Croatia (Hrvatska)"
  },
  {
    "imie": "Brock",
    "nazwisko": "Herrera",
    "nazwiskoRodowe": "Schwartz",
    "nrDomu": 68,
    "ulica": "Atkins Avenue",
    "kod": "57-891",
    "miasto": "Wanamie",
    "dataUrodzenia": "14.10.1916",
    "miejsceUrodzenia": "Ezel",
    "PESEL": 77032323528,
    "NIP": 1961349464,
    "imieOjca": "Robin",
    "imieMatki": "Francis",
    "plec": "Pan",
    "nazwiskoMatki": "Lloyd",
    "rodzajDokumentuTozsamosci": "paszport",
    "wydanyPrzez": "BurmistrzX",
    "nrDokumentu": "XYZ515660",
    "email": "francislloyd@nexgene.com",
    "telefon": "(964) 492-2301",
    "wyksztalcenie": "zasadnicze zawodowe",
    "obywatelstwo": "francuskie",
    "narodowosc": "Wallis and Futuna Islands"
  },
  {
    "imie": "Charmaine",
    "nazwisko": "Pruitt",
    "nazwiskoRodowe": "Fitzgerald",
    "nrDomu": 193,
    "ulica": "Interborough Parkway",
    "kod": "24-421",
    "miasto": "Kapowsin",
    "dataUrodzenia": "20.12.1934",
    "miejsceUrodzenia": "Ellerslie",
    "PESEL": 30082433825,
    "NIP": 9755894934,
    "imieOjca": "Reba",
    "imieMatki": "Josie",
    "plec": "Pan",
    "nazwiskoMatki": "Schmidt",
    "rodzajDokumentuTozsamosci": "paszport",
    "wydanyPrzez": "BurmistrzX",
    "nrDokumentu": "XYZ773917",
    "email": "josieschmidt@nexgene.com",
    "telefon": "(946) 509-3840",
    "wyksztalcenie": "podstawowe",
    "obywatelstwo": "francuskie",
    "narodowosc": "Georgia"
  },
  {
    "imie": "Eve",
    "nazwisko": "Crawford",
    "nazwiskoRodowe": "Henderson",
    "nrDomu": 132,
    "ulica": "Dupont Street",
    "kod": "31-916",
    "miasto": "Leland",
    "dataUrodzenia": "21.11.1943",
    "miejsceUrodzenia": "Sexton",
    "PESEL": 39052473716,
    "NIP": 6245296610,
    "imieOjca": "Lancaster",
    "imieMatki": "Lynch",
    "plec": "Pan",
    "nazwiskoMatki": "Miller",
    "rodzajDokumentuTozsamosci": "dowod osobisty",
    "wydanyPrzez": "BurmistrzZ",
    "nrDokumentu": "XYZ926164",
    "email": "lynchmiller@nexgene.com",
    "telefon": "(810) 415-3742",
    "wyksztalcenie": "zasadnicze zawodowe",
    "obywatelstwo": "niemieckie",
    "narodowosc": "Monaco"
  },
  {
    "imie": "Alta",
    "nazwisko": "Richardson",
    "nazwiskoRodowe": "Conway",
    "nrDomu": 191,
    "ulica": "Ashford Street",
    "kod": "85-485",
    "miasto": "Troy",
    "dataUrodzenia": "13.12.1994",
    "miejsceUrodzenia": "Dexter",
    "PESEL": 86062818350,
    "NIP": 4045024876,
    "imieOjca": "Paige",
    "imieMatki": "Howell",
    "plec": "Pani",
    "nazwiskoMatki": "Ferrell",
    "rodzajDokumentuTozsamosci": "paszport",
    "wydanyPrzez": "BurmistrzZ",
    "nrDokumentu": "XYZ428349",
    "email": "howellferrell@nexgene.com",
    "telefon": "(994) 488-2157",
    "wyksztalcenie": "średnie",
    "obywatelstwo": "niemieckie",
    "narodowosc": "Syria"
  },
  {
    "imie": "Eula",
    "nazwisko": "Saunders",
    "nazwiskoRodowe": "Daugherty",
    "nrDomu": 86,
    "ulica": "Aberdeen Street",
    "kod": "89-789",
    "miasto": "Kipp",
    "dataUrodzenia": "17.12.1994",
    "miejsceUrodzenia": "Bangor",
    "PESEL": 89022842028,
    "NIP": 6020557602,
    "imieOjca": "Gordon",
    "imieMatki": "Bonnie",
    "plec": "Pan",
    "nazwiskoMatki": "Shaffer",
    "rodzajDokumentuTozsamosci": "dowod osobisty",
    "wydanyPrzez": "BurmistrzX",
    "nrDokumentu": "XYZ193359",
    "email": "bonnieshaffer@nexgene.com",
    "telefon": "(940) 416-3922",
    "wyksztalcenie": "gimnazjalne",
    "obywatelstwo": "polskie",
    "narodowosc": "Azerbaijan"
  },
  {
    "imie": "Amparo",
    "nazwisko": "Mccarty",
    "nazwiskoRodowe": "Leblanc",
    "nrDomu": 40,
    "ulica": "Bassett Avenue",
    "kod": "65-729",
    "miasto": "Dana",
    "dataUrodzenia": "2.11.1939",
    "miejsceUrodzenia": "Mulino",
    "PESEL": 17042266510,
    "NIP": 1125676526,
    "imieOjca": "Pate",
    "imieMatki": "May",
    "plec": "Pani",
    "nazwiskoMatki": "Barlow",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ420993",
    "email": "maybarlow@nexgene.com",
    "telefon": "(954) 477-3766",
    "wyksztalcenie": "podstawowe",
    "obywatelstwo": "polskie",
    "narodowosc": "Nigeria"
  },
  {
    "imie": "Johanna",
    "nazwisko": "Ballard",
    "nazwiskoRodowe": "Oconnor",
    "nrDomu": 52,
    "ulica": "Colin Place",
    "kod": "96-314",
    "miasto": "Rote",
    "dataUrodzenia": "30.12.1960",
    "miejsceUrodzenia": "Gardiner",
    "PESEL": 29091966937,
    "NIP": 8476857937,
    "imieOjca": "Hayden",
    "imieMatki": "Lynnette",
    "plec": "Pani",
    "nazwiskoMatki": "Oneal",
    "rodzajDokumentuTozsamosci": "paszport",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ152730",
    "email": "lynnetteoneal@nexgene.com",
    "telefon": "(899) 553-3674",
    "wyksztalcenie": "zasadnicze zawodowe",
    "obywatelstwo": "polskie",
    "narodowosc": "Namibia"
  },
  {
    "imie": "Butler",
    "nazwisko": "Douglas",
    "nazwiskoRodowe": "Gill",
    "nrDomu": 46,
    "ulica": "Ridgecrest Terrace",
    "kod": "96-585",
    "miasto": "Bellamy",
    "dataUrodzenia": "5.12.1966",
    "miejsceUrodzenia": "Clayville",
    "PESEL": 33021084330,
    "NIP": 2691445657,
    "imieOjca": "Geneva",
    "imieMatki": "Tammi",
    "plec": "Pani",
    "nazwiskoMatki": "Schneider",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ556444",
    "email": "tammischneider@nexgene.com",
    "telefon": "(810) 465-2615",
    "wyksztalcenie": "gimnazjalne",
    "obywatelstwo": "polskie",
    "narodowosc": "Saint Kitts and Nevis"
  },
  {
    "imie": "Duran",
    "nazwisko": "Benjamin",
    "nazwiskoRodowe": "Hughes",
    "nrDomu": 151,
    "ulica": "Revere Place",
    "kod": "28-386",
    "miasto": "Kidder",
    "dataUrodzenia": "12.12.1994",
    "miejsceUrodzenia": "Wiscon",
    "PESEL": 49032868715,
    "NIP": 4672970543,
    "imieOjca": "Weeks",
    "imieMatki": "Janet",
    "plec": "Pan",
    "nazwiskoMatki": "Stewart",
    "rodzajDokumentuTozsamosci": "paszport",
    "wydanyPrzez": "BurmistrzZ",
    "nrDokumentu": "XYZ768900",
    "email": "janetstewart@nexgene.com",
    "telefon": "(911) 588-3035",
    "wyksztalcenie": "średnie",
    "obywatelstwo": "niemieckie",
    "narodowosc": "East Timor"
  },
  {
    "imie": "Justine",
    "nazwisko": "Jefferson",
    "nazwiskoRodowe": "Snow",
    "nrDomu": 176,
    "ulica": "Hamilton Walk",
    "kod": "58-243",
    "miasto": "Chilton",
    "dataUrodzenia": "18.10.1990",
    "miejsceUrodzenia": "Joppa",
    "PESEL": 96042125142,
    "NIP": 5324676599,
    "imieOjca": "Dejesus",
    "imieMatki": "Robinson",
    "plec": "Pan",
    "nazwiskoMatki": "Owen",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzX",
    "nrDokumentu": "XYZ625493",
    "email": "robinsonowen@nexgene.com",
    "telefon": "(901) 521-2125",
    "wyksztalcenie": "zasadnicze zawodowe",
    "obywatelstwo": "francuskie",
    "narodowosc": "Cote D'Ivoire (Ivory Coast)"
  },
  {
    "imie": "Vivian",
    "nazwisko": "Dudley",
    "nazwiskoRodowe": "Snider",
    "nrDomu": 110,
    "ulica": "Elliott Place",
    "kod": "45-335",
    "miasto": "Bradenville",
    "dataUrodzenia": "23.12.1980",
    "miejsceUrodzenia": "Whitmer",
    "PESEL": 82021282652,
    "NIP": 3164490994,
    "imieOjca": "Jordan",
    "imieMatki": "Betty",
    "plec": "Pani",
    "nazwiskoMatki": "Gonzalez",
    "rodzajDokumentuTozsamosci": "dowod osobisty",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ828864",
    "email": "bettygonzalez@nexgene.com",
    "telefon": "(966) 462-2262",
    "wyksztalcenie": "wyższe",
    "obywatelstwo": "niemieckie",
    "narodowosc": "Afghanistan"
  },
  {
    "imie": "Flora",
    "nazwisko": "Burns",
    "nazwiskoRodowe": "Henry",
    "nrDomu": 166,
    "ulica": "McKibbin Street",
    "kod": "85-241",
    "miasto": "Grill",
    "dataUrodzenia": "27.10.1911",
    "miejsceUrodzenia": "Tryon",
    "PESEL": 61052639663,
    "NIP": 5356656127,
    "imieOjca": "Savage",
    "imieMatki": "Casey",
    "plec": "Pani",
    "nazwiskoMatki": "Hicks",
    "rodzajDokumentuTozsamosci": "dowod osobisty",
    "wydanyPrzez": "BurmistrzX",
    "nrDokumentu": "XYZ797878",
    "email": "caseyhicks@nexgene.com",
    "telefon": "(905) 418-3653",
    "wyksztalcenie": "zasadnicze zawodowe",
    "obywatelstwo": "polskie",
    "narodowosc": "French Southern Territories"
  },
  {
    "imie": "Glenda",
    "nazwisko": "Farrell",
    "nazwiskoRodowe": "Watts",
    "nrDomu": 135,
    "ulica": "Bleecker Street",
    "kod": "14-395",
    "miasto": "Jessie",
    "dataUrodzenia": "30.11.2013",
    "miejsceUrodzenia": "Belva",
    "PESEL": 45021574720,
    "NIP": 5387995729,
    "imieOjca": "Marci",
    "imieMatki": "Amber",
    "plec": "Pani",
    "nazwiskoMatki": "David",
    "rodzajDokumentuTozsamosci": "dowod osobisty",
    "wydanyPrzez": "BurmistrzX",
    "nrDokumentu": "XYZ376329",
    "email": "amberdavid@nexgene.com",
    "telefon": "(850) 538-3411",
    "wyksztalcenie": "gimnazjalne",
    "obywatelstwo": "francuskie",
    "narodowosc": "Laos"
  },
  {
    "imie": "Dean",
    "nazwisko": "Page",
    "nazwiskoRodowe": "Donovan",
    "nrDomu": 78,
    "ulica": "Ebony Court",
    "kod": "83-579",
    "miasto": "Muse",
    "dataUrodzenia": "4.12.2011",
    "miejsceUrodzenia": "Riviera",
    "PESEL": 29043074178,
    "NIP": 1336313940,
    "imieOjca": "Vonda",
    "imieMatki": "Andrea",
    "plec": "Pani",
    "nazwiskoMatki": "Morris",
    "rodzajDokumentuTozsamosci": "paszport",
    "wydanyPrzez": "BurmistrzX",
    "nrDokumentu": "XYZ296907",
    "email": "andreamorris@nexgene.com",
    "telefon": "(816) 415-3841",
    "wyksztalcenie": "wyższe",
    "obywatelstwo": "polskie",
    "narodowosc": "Nicaragua"
  },
  {
    "imie": "Earlene",
    "nazwisko": "Maynard",
    "nazwiskoRodowe": "Mcpherson",
    "nrDomu": 9,
    "ulica": "Saratoga Avenue",
    "kod": "42-604",
    "miasto": "Chaparrito",
    "dataUrodzenia": "3.11.1946",
    "miejsceUrodzenia": "Bedias",
    "PESEL": 37061489436,
    "NIP": 4190679205,
    "imieOjca": "Cote",
    "imieMatki": "Isabel",
    "plec": "Pan",
    "nazwiskoMatki": "Madden",
    "rodzajDokumentuTozsamosci": "dowod osobisty",
    "wydanyPrzez": "BurmistrzX",
    "nrDokumentu": "XYZ355850",
    "email": "isabelmadden@nexgene.com",
    "telefon": "(931) 520-2707",
    "wyksztalcenie": "średnie",
    "obywatelstwo": "polskie",
    "narodowosc": "Egypt"
  },
  {
    "imie": "Nadine",
    "nazwisko": "Franks",
    "nazwiskoRodowe": "Flores",
    "nrDomu": 152,
    "ulica": "Newport Street",
    "kod": "77-856",
    "miasto": "Sanborn",
    "dataUrodzenia": "21.11.1991",
    "miejsceUrodzenia": "Cetronia",
    "PESEL": 49022613962,
    "NIP": 1094357141,
    "imieOjca": "Joanne",
    "imieMatki": "Celina",
    "plec": "Pan",
    "nazwiskoMatki": "Wilkerson",
    "rodzajDokumentuTozsamosci": "dowod osobisty",
    "wydanyPrzez": "BurmistrzZ",
    "nrDokumentu": "XYZ408370",
    "email": "celinawilkerson@nexgene.com",
    "telefon": "(929) 429-2796",
    "wyksztalcenie": "średnie",
    "obywatelstwo": "niemieckie",
    "narodowosc": "Canada"
  },
  {
    "imie": "Helene",
    "nazwisko": "Mcknight",
    "nazwiskoRodowe": "House",
    "nrDomu": 163,
    "ulica": "Main Street",
    "kod": "78-422",
    "miasto": "Germanton",
    "dataUrodzenia": "15.11.1967",
    "miejsceUrodzenia": "Gadsden",
    "PESEL": 58072376116,
    "NIP": 3304241157,
    "imieOjca": "Conley",
    "imieMatki": "Mayer",
    "plec": "Pan",
    "nazwiskoMatki": "Horne",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzX",
    "nrDokumentu": "XYZ682639",
    "email": "mayerhorne@nexgene.com",
    "telefon": "(802) 504-3051",
    "wyksztalcenie": "wyższe",
    "obywatelstwo": "polskie",
    "narodowosc": "Sierra Leone"
  },
  {
    "imie": "Albert",
    "nazwisko": "Fletcher",
    "nazwiskoRodowe": "Williamson",
    "nrDomu": 137,
    "ulica": "Richmond Street",
    "kod": "38-312",
    "miasto": "Weogufka",
    "dataUrodzenia": "17.12.1921",
    "miejsceUrodzenia": "Tivoli",
    "PESEL": 25041325275,
    "NIP": 3747999384,
    "imieOjca": "Olson",
    "imieMatki": "Rhea",
    "plec": "Pan",
    "nazwiskoMatki": "Stone",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzZ",
    "nrDokumentu": "XYZ159253",
    "email": "rheastone@nexgene.com",
    "telefon": "(949) 472-3083",
    "wyksztalcenie": "gimnazjalne",
    "obywatelstwo": "polskie",
    "narodowosc": "Kenya"
  },
  {
    "imie": "Christi",
    "nazwisko": "Mullen",
    "nazwiskoRodowe": "Rose",
    "nrDomu": 183,
    "ulica": "Dewitt Avenue",
    "kod": "76-791",
    "miasto": "Keller",
    "dataUrodzenia": "4.10.1946",
    "miejsceUrodzenia": "Grahamtown",
    "PESEL": 98031711287,
    "NIP": 6748672450,
    "imieOjca": "Durham",
    "imieMatki": "Jill",
    "plec": "Pani",
    "nazwiskoMatki": "Hoffman",
    "rodzajDokumentuTozsamosci": "paszport",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ711254",
    "email": "jillhoffman@nexgene.com",
    "telefon": "(843) 535-3451",
    "wyksztalcenie": "wyższe",
    "obywatelstwo": "niemieckie",
    "narodowosc": "Libya"
  },
  {
    "imie": "Lorraine",
    "nazwisko": "Armstrong",
    "nazwiskoRodowe": "Maldonado",
    "nrDomu": 88,
    "ulica": "Langham Street",
    "kod": "17-289",
    "miasto": "Gulf",
    "dataUrodzenia": "14.12.1911",
    "miejsceUrodzenia": "Bentonville",
    "PESEL": 24021897895,
    "NIP": 5771968551,
    "imieOjca": "Mcpherson",
    "imieMatki": "Hahn",
    "plec": "Pan",
    "nazwiskoMatki": "Whitley",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzX",
    "nrDokumentu": "XYZ609381",
    "email": "hahnwhitley@nexgene.com",
    "telefon": "(945) 580-2981",
    "wyksztalcenie": "średnie",
    "obywatelstwo": "polskie",
    "narodowosc": "Kiribati"
  },
  {
    "imie": "Sparks",
    "nazwisko": "Moon",
    "nazwiskoRodowe": "Price",
    "nrDomu": 197,
    "ulica": "Wolf Place",
    "kod": "65-863",
    "miasto": "Taft",
    "dataUrodzenia": "30.12.1944",
    "miejsceUrodzenia": "Canterwood",
    "PESEL": 13012015466,
    "NIP": 4145794588,
    "imieOjca": "Ferrell",
    "imieMatki": "Bowman",
    "plec": "Pani",
    "nazwiskoMatki": "Kline",
    "rodzajDokumentuTozsamosci": "dowod osobisty",
    "wydanyPrzez": "BurmistrzX",
    "nrDokumentu": "XYZ183652",
    "email": "bowmankline@nexgene.com",
    "telefon": "(988) 533-4000",
    "wyksztalcenie": "podstawowe",
    "obywatelstwo": "francuskie",
    "narodowosc": "Peru"
  },
  {
    "imie": "Andrews",
    "nazwisko": "Lane",
    "nazwiskoRodowe": "Knapp",
    "nrDomu": 134,
    "ulica": "Jamison Lane",
    "kod": "59-851",
    "miasto": "Felt",
    "dataUrodzenia": "24.12.1941",
    "miejsceUrodzenia": "Elliott",
    "PESEL": 62032422911,
    "NIP": 7539013413,
    "imieOjca": "Duffy",
    "imieMatki": "Maxine",
    "plec": "Pani",
    "nazwiskoMatki": "Peters",
    "rodzajDokumentuTozsamosci": "paszport",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ356728",
    "email": "maxinepeters@nexgene.com",
    "telefon": "(960) 590-3400",
    "wyksztalcenie": "zasadnicze zawodowe",
    "obywatelstwo": "polskie",
    "narodowosc": "Belgium"
  },
  {
    "imie": "Wendi",
    "nazwisko": "Osborn",
    "nazwiskoRodowe": "Salas",
    "nrDomu": 163,
    "ulica": "Central Avenue",
    "kod": "52-844",
    "miasto": "Falconaire",
    "dataUrodzenia": "21.11.2010",
    "miejsceUrodzenia": "Bend",
    "PESEL": 60041353310,
    "NIP": 9488929113,
    "imieOjca": "Hooper",
    "imieMatki": "Shepard",
    "plec": "Pan",
    "nazwiskoMatki": "Atkins",
    "rodzajDokumentuTozsamosci": "paszport",
    "wydanyPrzez": "BurmistrzZ",
    "nrDokumentu": "XYZ680721",
    "email": "shepardatkins@nexgene.com",
    "telefon": "(996) 544-3924",
    "wyksztalcenie": "gimnazjalne",
    "obywatelstwo": "francuskie",
    "narodowosc": "Comoros"
  },
  {
    "imie": "Salas",
    "nazwisko": "Monroe",
    "nazwiskoRodowe": "Hensley",
    "nrDomu": 42,
    "ulica": "Garfield Place",
    "kod": "22-782",
    "miasto": "Jamestown",
    "dataUrodzenia": "22.12.1984",
    "miejsceUrodzenia": "Fannett",
    "PESEL": 32062283461,
    "NIP": 4840911157,
    "imieOjca": "Rhodes",
    "imieMatki": "Adriana",
    "plec": "Pani",
    "nazwiskoMatki": "Hartman",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ716047",
    "email": "adrianahartman@nexgene.com",
    "telefon": "(870) 589-3637",
    "wyksztalcenie": "średnie",
    "obywatelstwo": "niemieckie",
    "narodowosc": "Burundi"
  },
  {
    "imie": "Glover",
    "nazwisko": "Cameron",
    "nazwiskoRodowe": "Stanley",
    "nrDomu": 180,
    "ulica": "Calyer Street",
    "kod": "34-181",
    "miasto": "Nicholson",
    "dataUrodzenia": "17.10.1952",
    "miejsceUrodzenia": "Nipinnawasee",
    "PESEL": 36071114472,
    "NIP": 1524394503,
    "imieOjca": "Rutledge",
    "imieMatki": "Pat",
    "plec": "Pan",
    "nazwiskoMatki": "Hansen",
    "rodzajDokumentuTozsamosci": "paszport",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ746428",
    "email": "pathansen@nexgene.com",
    "telefon": "(874) 504-2496",
    "wyksztalcenie": "średnie",
    "obywatelstwo": "polskie",
    "narodowosc": "Guam"
  },
  {
    "imie": "Alexandria",
    "nazwisko": "Jacobs",
    "nazwiskoRodowe": "Roth",
    "nrDomu": 152,
    "ulica": "Wyona Street",
    "kod": "97-969",
    "miasto": "Soudan",
    "dataUrodzenia": "6.11.1981",
    "miejsceUrodzenia": "Grayhawk",
    "PESEL": 59042318519,
    "NIP": 9235611152,
    "imieOjca": "Ester",
    "imieMatki": "Fitzgerald",
    "plec": "Pani",
    "nazwiskoMatki": "Macias",
    "rodzajDokumentuTozsamosci": "paszport",
    "wydanyPrzez": "BurmistrzZ",
    "nrDokumentu": "XYZ580600",
    "email": "fitzgeraldmacias@nexgene.com",
    "telefon": "(960) 556-2976",
    "wyksztalcenie": "średnie",
    "obywatelstwo": "niemieckie",
    "narodowosc": "Puerto Rico"
  },
  {
    "imie": "Curtis",
    "nazwisko": "Delacruz",
    "nazwiskoRodowe": "Bush",
    "nrDomu": 103,
    "ulica": "Hawthorne Street",
    "kod": "94-239",
    "miasto": "Kent",
    "dataUrodzenia": "14.12.1996",
    "miejsceUrodzenia": "Canby",
    "PESEL": 65072460537,
    "NIP": 1297378233,
    "imieOjca": "Jami",
    "imieMatki": "Mckee",
    "plec": "Pan",
    "nazwiskoMatki": "Francis",
    "rodzajDokumentuTozsamosci": "paszport",
    "wydanyPrzez": "BurmistrzX",
    "nrDokumentu": "XYZ518674",
    "email": "mckeefrancis@nexgene.com",
    "telefon": "(880) 547-2020",
    "wyksztalcenie": "podstawowe",
    "obywatelstwo": "niemieckie",
    "narodowosc": "French Guiana"
  },
  {
    "imie": "Darcy",
    "nazwisko": "Santiago",
    "nazwiskoRodowe": "Floyd",
    "nrDomu": 88,
    "ulica": "Ocean Avenue",
    "kod": "25-592",
    "miasto": "Lafferty",
    "dataUrodzenia": "26.12.1921",
    "miejsceUrodzenia": "Iola",
    "PESEL": 64052332059,
    "NIP": 1174616742,
    "imieOjca": "Leigh",
    "imieMatki": "Davidson",
    "plec": "Pan",
    "nazwiskoMatki": "Cooley",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzX",
    "nrDokumentu": "XYZ285057",
    "email": "davidsoncooley@nexgene.com",
    "telefon": "(808) 464-2083",
    "wyksztalcenie": "zasadnicze zawodowe",
    "obywatelstwo": "polskie",
    "narodowosc": "Tunisia"
  },
  {
    "imie": "Wolfe",
    "nazwisko": "Harrison",
    "nazwiskoRodowe": "Mendoza",
    "nrDomu": 8,
    "ulica": "Nautilus Avenue",
    "kod": "70-701",
    "miasto": "Temperanceville",
    "dataUrodzenia": "4.12.1964",
    "miejsceUrodzenia": "Nicut",
    "PESEL": 28011112241,
    "NIP": 3118152961,
    "imieOjca": "Ramsey",
    "imieMatki": "Golden",
    "plec": "Pan",
    "nazwiskoMatki": "Reid",
    "rodzajDokumentuTozsamosci": "dowod osobisty",
    "wydanyPrzez": "BurmistrzZ",
    "nrDokumentu": "XYZ329012",
    "email": "goldenreid@nexgene.com",
    "telefon": "(853) 461-3156",
    "wyksztalcenie": "wyższe",
    "obywatelstwo": "polskie",
    "narodowosc": "Japan"
  },
  {
    "imie": "Patti",
    "nazwisko": "Bishop",
    "nazwiskoRodowe": "Cantrell",
    "nrDomu": 30,
    "ulica": "Waldane Court",
    "kod": "80-964",
    "miasto": "Williston",
    "dataUrodzenia": "28.10.1925",
    "miejsceUrodzenia": "Rosewood",
    "PESEL": 93051288667,
    "NIP": 1490592581,
    "imieOjca": "Denise",
    "imieMatki": "Foley",
    "plec": "Pan",
    "nazwiskoMatki": "Payne",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzX",
    "nrDokumentu": "XYZ931301",
    "email": "foleypayne@nexgene.com",
    "telefon": "(863) 475-2748",
    "wyksztalcenie": "podstawowe",
    "obywatelstwo": "francuskie",
    "narodowosc": "Swaziland"
  },
  {
    "imie": "Claudette",
    "nazwisko": "Bernard",
    "nazwiskoRodowe": "Good",
    "nrDomu": 125,
    "ulica": "Grant Avenue",
    "kod": "11-189",
    "miasto": "Craig",
    "dataUrodzenia": "9.12.1903",
    "miejsceUrodzenia": "Manila",
    "PESEL": 88022311544,
    "NIP": 3160585987,
    "imieOjca": "Dickerson",
    "imieMatki": "William",
    "plec": "Pan",
    "nazwiskoMatki": "Mathis",
    "rodzajDokumentuTozsamosci": "paszport",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ461173",
    "email": "williammathis@nexgene.com",
    "telefon": "(917) 594-3536",
    "wyksztalcenie": "zasadnicze zawodowe",
    "obywatelstwo": "niemieckie",
    "narodowosc": "Macau"
  },
  {
    "imie": "Nona",
    "nazwisko": "Baird",
    "nazwiskoRodowe": "Mccarthy",
    "nrDomu": 18,
    "ulica": "Throop Avenue",
    "kod": "65-945",
    "miasto": "Brule",
    "dataUrodzenia": "3.10.1939",
    "miejsceUrodzenia": "Biehle",
    "PESEL": 12031785022,
    "NIP": 3925473556,
    "imieOjca": "George",
    "imieMatki": "Avis",
    "plec": "Pani",
    "nazwiskoMatki": "Juarez",
    "rodzajDokumentuTozsamosci": "dowod osobisty",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ843023",
    "email": "avisjuarez@nexgene.com",
    "telefon": "(820) 567-3562",
    "wyksztalcenie": "podstawowe",
    "obywatelstwo": "francuskie",
    "narodowosc": "Morocco"
  },
  {
    "imie": "Tamika",
    "nazwisko": "Stafford",
    "nazwiskoRodowe": "Cash",
    "nrDomu": 105,
    "ulica": "Barbey Street",
    "kod": "32-735",
    "miasto": "Gilgo",
    "dataUrodzenia": "28.11.1931",
    "miejsceUrodzenia": "Hebron",
    "PESEL": 62013062301,
    "NIP": 3154236724,
    "imieOjca": "Meredith",
    "imieMatki": "Collier",
    "plec": "Pani",
    "nazwiskoMatki": "Foreman",
    "rodzajDokumentuTozsamosci": "paszport",
    "wydanyPrzez": "BurmistrzX",
    "nrDokumentu": "XYZ541535",
    "email": "collierforeman@nexgene.com",
    "telefon": "(978) 498-2049",
    "wyksztalcenie": "zasadnicze zawodowe",
    "obywatelstwo": "francuskie",
    "narodowosc": "Iraq"
  },
  {
    "imie": "Nichols",
    "nazwisko": "Hatfield",
    "nazwiskoRodowe": "Bailey",
    "nrDomu": 39,
    "ulica": "Willoughby Street",
    "kod": "22-571",
    "miasto": "Idamay",
    "dataUrodzenia": "22.10.1910",
    "miejsceUrodzenia": "Leming",
    "PESEL": 98062664660,
    "NIP": 9779211423,
    "imieOjca": "Alyssa",
    "imieMatki": "Charlene",
    "plec": "Pani",
    "nazwiskoMatki": "Talley",
    "rodzajDokumentuTozsamosci": "dowod osobisty",
    "wydanyPrzez": "BurmistrzX",
    "nrDokumentu": "XYZ152344",
    "email": "charlenetalley@nexgene.com",
    "telefon": "(911) 533-3740",
    "wyksztalcenie": "podstawowe",
    "obywatelstwo": "francuskie",
    "narodowosc": "Thailand"
  },
  {
    "imie": "Ines",
    "nazwisko": "Hurst",
    "nazwiskoRodowe": "Everett",
    "nrDomu": 4,
    "ulica": "Schenck Court",
    "kod": "51-467",
    "miasto": "Tioga",
    "dataUrodzenia": "24.12.1972",
    "miejsceUrodzenia": "Sutton",
    "PESEL": 60032114736,
    "NIP": 3640390473,
    "imieOjca": "Mcfadden",
    "imieMatki": "Torres",
    "plec": "Pan",
    "nazwiskoMatki": "Baldwin",
    "rodzajDokumentuTozsamosci": "paszport",
    "wydanyPrzez": "BurmistrzX",
    "nrDokumentu": "XYZ147500",
    "email": "torresbaldwin@nexgene.com",
    "telefon": "(832) 468-3937",
    "wyksztalcenie": "podstawowe",
    "obywatelstwo": "niemieckie",
    "narodowosc": "Northern Mariana Islands"
  },
  {
    "imie": "Barry",
    "nazwisko": "Luna",
    "nazwiskoRodowe": "Wyatt",
    "nrDomu": 23,
    "ulica": "Wortman Avenue",
    "kod": "40-196",
    "miasto": "Emerald",
    "dataUrodzenia": "15.11.1948",
    "miejsceUrodzenia": "Frizzleburg",
    "PESEL": 75051829341,
    "NIP": 2392025919,
    "imieOjca": "Leticia",
    "imieMatki": "Fowler",
    "plec": "Pan",
    "nazwiskoMatki": "Medina",
    "rodzajDokumentuTozsamosci": "dowod osobisty",
    "wydanyPrzez": "BurmistrzZ",
    "nrDokumentu": "XYZ290007",
    "email": "fowlermedina@nexgene.com",
    "telefon": "(952) 541-3138",
    "wyksztalcenie": "średnie",
    "obywatelstwo": "niemieckie",
    "narodowosc": "Slovenia"
  },
  {
    "imie": "Ruth",
    "nazwisko": "Crane",
    "nazwiskoRodowe": "Hancock",
    "nrDomu": 13,
    "ulica": "Grimes Road",
    "kod": "48-262",
    "miasto": "Takilma",
    "dataUrodzenia": "25.12.1984",
    "miejsceUrodzenia": "Gracey",
    "PESEL": 22052624749,
    "NIP": 3830260450,
    "imieOjca": "Stacey",
    "imieMatki": "Jannie",
    "plec": "Pan",
    "nazwiskoMatki": "Burks",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzZ",
    "nrDokumentu": "XYZ191066",
    "email": "jannieburks@nexgene.com",
    "telefon": "(802) 466-2329",
    "wyksztalcenie": "wyższe",
    "obywatelstwo": "polskie",
    "narodowosc": "Liberia"
  },
  {
    "imie": "Ladonna",
    "nazwisko": "Melton",
    "nazwiskoRodowe": "Wallace",
    "nrDomu": 164,
    "ulica": "Bennet Court",
    "kod": "58-106",
    "miasto": "Vernon",
    "dataUrodzenia": "2.10.1990",
    "miejsceUrodzenia": "Umapine",
    "PESEL": 75032756025,
    "NIP": 8175429347,
    "imieOjca": "Blackwell",
    "imieMatki": "Baldwin",
    "plec": "Pani",
    "nazwiskoMatki": "Vaughan",
    "rodzajDokumentuTozsamosci": "paszport",
    "wydanyPrzez": "BurmistrzX",
    "nrDokumentu": "XYZ749846",
    "email": "baldwinvaughan@nexgene.com",
    "telefon": "(843) 600-2054",
    "wyksztalcenie": "gimnazjalne",
    "obywatelstwo": "niemieckie",
    "narodowosc": "Ukraine"
  },
  {
    "imie": "Jeri",
    "nazwisko": "Munoz",
    "nazwiskoRodowe": "Roberson",
    "nrDomu": 176,
    "ulica": "Putnam Avenue",
    "kod": "38-843",
    "miasto": "Nile",
    "dataUrodzenia": "20.11.1938",
    "miejsceUrodzenia": "Farmington",
    "PESEL": 85031447468,
    "NIP": 8512802684,
    "imieOjca": "Eddie",
    "imieMatki": "Dawson",
    "plec": "Pan",
    "nazwiskoMatki": "Dennis",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzZ",
    "nrDokumentu": "XYZ919626",
    "email": "dawsondennis@nexgene.com",
    "telefon": "(814) 420-3423",
    "wyksztalcenie": "zasadnicze zawodowe",
    "obywatelstwo": "niemieckie",
    "narodowosc": "Turkmenistan"
  },
  {
    "imie": "Holder",
    "nazwisko": "Perkins",
    "nazwiskoRodowe": "Vinson",
    "nrDomu": 16,
    "ulica": "Beach Place",
    "kod": "49-755",
    "miasto": "Longbranch",
    "dataUrodzenia": "9.11.1947",
    "miejsceUrodzenia": "Fidelis",
    "PESEL": 75031146284,
    "NIP": 6589810257,
    "imieOjca": "Bell",
    "imieMatki": "Nolan",
    "plec": "Pan",
    "nazwiskoMatki": "Holland",
    "rodzajDokumentuTozsamosci": "dowod osobisty",
    "wydanyPrzez": "BurmistrzX",
    "nrDokumentu": "XYZ722943",
    "email": "nolanholland@nexgene.com",
    "telefon": "(975) 404-2239",
    "wyksztalcenie": "średnie",
    "obywatelstwo": "polskie",
    "narodowosc": "Denmark"
  },
  {
    "imie": "Cecelia",
    "nazwisko": "Whitehead",
    "nazwiskoRodowe": "Gomez",
    "nrDomu": 185,
    "ulica": "Murdock Court",
    "kod": "91-816",
    "miasto": "Ferney",
    "dataUrodzenia": "16.12.1951",
    "miejsceUrodzenia": "Hampstead",
    "PESEL": 20021765906,
    "NIP": 7547415200,
    "imieOjca": "Roach",
    "imieMatki": "Misty",
    "plec": "Pan",
    "nazwiskoMatki": "Orr",
    "rodzajDokumentuTozsamosci": "dowod osobisty",
    "wydanyPrzez": "BurmistrzX",
    "nrDokumentu": "XYZ610721",
    "email": "mistyorr@nexgene.com",
    "telefon": "(934) 515-2444",
    "wyksztalcenie": "zasadnicze zawodowe",
    "obywatelstwo": "francuskie",
    "narodowosc": "Pitcairn"
  },
  {
    "imie": "Pierce",
    "nazwisko": "Decker",
    "nazwiskoRodowe": "Boyer",
    "nrDomu": 117,
    "ulica": "Amersfort Place",
    "kod": "32-236",
    "miasto": "Belmont",
    "dataUrodzenia": "27.11.1917",
    "miejsceUrodzenia": "Brogan",
    "PESEL": 28052293829,
    "NIP": 6895273548,
    "imieOjca": "Constance",
    "imieMatki": "Chandler",
    "plec": "Pan",
    "nazwiskoMatki": "Mcclure",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ327164",
    "email": "chandlermcclure@nexgene.com",
    "telefon": "(962) 556-2118",
    "wyksztalcenie": "zasadnicze zawodowe",
    "obywatelstwo": "polskie",
    "narodowosc": "Cuba"
  },
  {
    "imie": "Lindsey",
    "nazwisko": "Turner",
    "nazwiskoRodowe": "Deleon",
    "nrDomu": 134,
    "ulica": "Campus Place",
    "kod": "38-269",
    "miasto": "Manitou",
    "dataUrodzenia": "30.11.1901",
    "miejsceUrodzenia": "Hayes",
    "PESEL": 90082672482,
    "NIP": 9524547682,
    "imieOjca": "Janell",
    "imieMatki": "Mercer",
    "plec": "Pan",
    "nazwiskoMatki": "Solomon",
    "rodzajDokumentuTozsamosci": "paszport",
    "wydanyPrzez": "BurmistrzX",
    "nrDokumentu": "XYZ823975",
    "email": "mercersolomon@nexgene.com",
    "telefon": "(841) 586-2232",
    "wyksztalcenie": "zasadnicze zawodowe",
    "obywatelstwo": "niemieckie",
    "narodowosc": "Kuwait"
  },
  {
    "imie": "Phoebe",
    "nazwisko": "Franklin",
    "nazwiskoRodowe": "Gay",
    "nrDomu": 169,
    "ulica": "Newton Street",
    "kod": "94-365",
    "miasto": "Defiance",
    "dataUrodzenia": "7.10.1962",
    "miejsceUrodzenia": "Condon",
    "PESEL": 94022697232,
    "NIP": 5815693399,
    "imieOjca": "Pittman",
    "imieMatki": "Michele",
    "plec": "Pani",
    "nazwiskoMatki": "Day",
    "rodzajDokumentuTozsamosci": "dowod osobisty",
    "wydanyPrzez": "BurmistrzZ",
    "nrDokumentu": "XYZ930784",
    "email": "micheleday@nexgene.com",
    "telefon": "(806) 581-3885",
    "wyksztalcenie": "średnie",
    "obywatelstwo": "niemieckie",
    "narodowosc": "Sweden"
  },
  {
    "imie": "Tate",
    "nazwisko": "Jones",
    "nazwiskoRodowe": "Hebert",
    "nrDomu": 197,
    "ulica": "Metrotech Courtr",
    "kod": "68-135",
    "miasto": "Bourg",
    "dataUrodzenia": "3.11.1956",
    "miejsceUrodzenia": "Lisco",
    "PESEL": 73011524637,
    "NIP": 6828964557,
    "imieOjca": "Zamora",
    "imieMatki": "Annmarie",
    "plec": "Pani",
    "nazwiskoMatki": "Wheeler",
    "rodzajDokumentuTozsamosci": "dowod osobisty",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ362186",
    "email": "annmariewheeler@nexgene.com",
    "telefon": "(879) 593-2728",
    "wyksztalcenie": "podstawowe",
    "obywatelstwo": "niemieckie",
    "narodowosc": "Brazil"
  },
  {
    "imie": "Shepherd",
    "nazwisko": "Macdonald",
    "nazwiskoRodowe": "Snyder",
    "nrDomu": 18,
    "ulica": "Seton Place",
    "kod": "58-605",
    "miasto": "Mansfield",
    "dataUrodzenia": "2.10.1975",
    "miejsceUrodzenia": "Lowell",
    "PESEL": 38042910871,
    "NIP": 7736961603,
    "imieOjca": "Kristi",
    "imieMatki": "Krista",
    "plec": "Pani",
    "nazwiskoMatki": "Cabrera",
    "rodzajDokumentuTozsamosci": "dowod osobisty",
    "wydanyPrzez": "BurmistrzZ",
    "nrDokumentu": "XYZ930479",
    "email": "kristacabrera@nexgene.com",
    "telefon": "(903) 456-2846",
    "wyksztalcenie": "podstawowe",
    "obywatelstwo": "polskie",
    "narodowosc": "Austria"
  },
  {
    "imie": "Henderson",
    "nazwisko": "Tyler",
    "nazwiskoRodowe": "Johns",
    "nrDomu": 29,
    "ulica": "Harkness Avenue",
    "kod": "48-524",
    "miasto": "Thomasville",
    "dataUrodzenia": "7.11.1902",
    "miejsceUrodzenia": "Shepardsville",
    "PESEL": 53071343255,
    "NIP": 4886300139,
    "imieOjca": "Brenda",
    "imieMatki": "Mollie",
    "plec": "Pan",
    "nazwiskoMatki": "Evans",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzX",
    "nrDokumentu": "XYZ412710",
    "email": "mollieevans@nexgene.com",
    "telefon": "(857) 514-2868",
    "wyksztalcenie": "wyższe",
    "obywatelstwo": "francuskie",
    "narodowosc": "Martinique"
  },
  {
    "imie": "Lewis",
    "nazwisko": "Estrada",
    "nazwiskoRodowe": "Potter",
    "nrDomu": 3,
    "ulica": "Dahill Road",
    "kod": "47-167",
    "miasto": "Hilltop",
    "dataUrodzenia": "3.12.1974",
    "miejsceUrodzenia": "Magnolia",
    "PESEL": 18031027054,
    "NIP": 7970796354,
    "imieOjca": "Nieves",
    "imieMatki": "Cohen",
    "plec": "Pani",
    "nazwiskoMatki": "Mccullough",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzX",
    "nrDokumentu": "XYZ623196",
    "email": "cohenmccullough@nexgene.com",
    "telefon": "(861) 556-3975",
    "wyksztalcenie": "wyższe",
    "obywatelstwo": "francuskie",
    "narodowosc": "Australia"
  },
  {
    "imie": "Marks",
    "nazwisko": "Espinoza",
    "nazwiskoRodowe": "Casey",
    "nrDomu": 92,
    "ulica": "Turner Place",
    "kod": "87-679",
    "miasto": "Yukon",
    "dataUrodzenia": "14.11.1987",
    "miejsceUrodzenia": "Springdale",
    "PESEL": 68081638807,
    "NIP": 7258293875,
    "imieOjca": "Gill",
    "imieMatki": "Ola",
    "plec": "Pan",
    "nazwiskoMatki": "Arnold",
    "rodzajDokumentuTozsamosci": "paszport",
    "wydanyPrzez": "BurmistrzZ",
    "nrDokumentu": "XYZ305562",
    "email": "olaarnold@nexgene.com",
    "telefon": "(925) 501-2694",
    "wyksztalcenie": "gimnazjalne",
    "obywatelstwo": "francuskie",
    "narodowosc": "Poland"
  },
  {
    "imie": "Sonya",
    "nazwisko": "Washington",
    "nazwiskoRodowe": "Chang",
    "nrDomu": 11,
    "ulica": "Willow Place",
    "kod": "87-409",
    "miasto": "Blackgum",
    "dataUrodzenia": "11.10.1993",
    "miejsceUrodzenia": "Kansas",
    "PESEL": 68091087191,
    "NIP": 4312333076,
    "imieOjca": "Janice",
    "imieMatki": "Neal",
    "plec": "Pan",
    "nazwiskoMatki": "Mcbride",
    "rodzajDokumentuTozsamosci": "paszport",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ338283",
    "email": "nealmcbride@nexgene.com",
    "telefon": "(990) 442-3367",
    "wyksztalcenie": "wyższe",
    "obywatelstwo": "niemieckie",
    "narodowosc": "American Samoa"
  },
  {
    "imie": "Sophie",
    "nazwisko": "Noble",
    "nazwiskoRodowe": "Sargent",
    "nrDomu": 8,
    "ulica": "Prospect Street",
    "kod": "13-578",
    "miasto": "Roulette",
    "dataUrodzenia": "30.10.1910",
    "miejsceUrodzenia": "Duryea",
    "PESEL": 53052514499,
    "NIP": 4299153356,
    "imieOjca": "Jaime",
    "imieMatki": "Lindsay",
    "plec": "Pan",
    "nazwiskoMatki": "Lamb",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzZ",
    "nrDokumentu": "XYZ840791",
    "email": "lindsaylamb@nexgene.com",
    "telefon": "(856) 491-2864",
    "wyksztalcenie": "średnie",
    "obywatelstwo": "niemieckie",
    "narodowosc": "Argentina"
  },
  {
    "imie": "Wooten",
    "nazwisko": "Kane",
    "nazwiskoRodowe": "Curtis",
    "nrDomu": 46,
    "ulica": "Woodhull Street",
    "kod": "80-487",
    "miasto": "Morningside",
    "dataUrodzenia": "26.12.1953",
    "miejsceUrodzenia": "Taycheedah",
    "PESEL": 67031986496,
    "NIP": 8943127524,
    "imieOjca": "Cecilia",
    "imieMatki": "Frazier",
    "plec": "Pan",
    "nazwiskoMatki": "Clark",
    "rodzajDokumentuTozsamosci": "dowod osobisty",
    "wydanyPrzez": "BurmistrzZ",
    "nrDokumentu": "XYZ944048",
    "email": "frazierclark@nexgene.com",
    "telefon": "(925) 478-2189",
    "wyksztalcenie": "gimnazjalne",
    "obywatelstwo": "niemieckie",
    "narodowosc": "Greenland"
  },
  {
    "imie": "Patty",
    "nazwisko": "Shepard",
    "nazwiskoRodowe": "Thompson",
    "nrDomu": 148,
    "ulica": "Poly Place",
    "kod": "59-148",
    "miasto": "Herbster",
    "dataUrodzenia": "17.12.1911",
    "miejsceUrodzenia": "Swartzville",
    "PESEL": 43052641427,
    "NIP": 3660578289,
    "imieOjca": "Haynes",
    "imieMatki": "Gwendolyn",
    "plec": "Pan",
    "nazwiskoMatki": "Wagner",
    "rodzajDokumentuTozsamosci": "paszport",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ218431",
    "email": "gwendolynwagner@nexgene.com",
    "telefon": "(899) 495-2558",
    "wyksztalcenie": "zasadnicze zawodowe",
    "obywatelstwo": "niemieckie",
    "narodowosc": "Israel"
  },
  {
    "imie": "Amalia",
    "nazwisko": "Maddox",
    "nazwiskoRodowe": "Acosta",
    "nrDomu": 90,
    "ulica": "Knight Court",
    "kod": "68-390",
    "miasto": "Snelling",
    "dataUrodzenia": "30.11.1972",
    "miejsceUrodzenia": "Shasta",
    "PESEL": 94011364887,
    "NIP": 7494356285,
    "imieOjca": "Richmond",
    "imieMatki": "Nunez",
    "plec": "Pani",
    "nazwiskoMatki": "Sears",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzZ",
    "nrDokumentu": "XYZ681591",
    "email": "nunezsears@nexgene.com",
    "telefon": "(929) 561-2004",
    "wyksztalcenie": "zasadnicze zawodowe",
    "obywatelstwo": "polskie",
    "narodowosc": "S. Georgia and S. Sandwich Isls."
  },
  {
    "imie": "Patton",
    "nazwisko": "Hahn",
    "nazwiskoRodowe": "Sanford",
    "nrDomu": 184,
    "ulica": "Bragg Court",
    "kod": "19-882",
    "miasto": "Aguila",
    "dataUrodzenia": "22.10.1947",
    "miejsceUrodzenia": "Deputy",
    "PESEL": 15081918125,
    "NIP": 4485917580,
    "imieOjca": "Roth",
    "imieMatki": "Monique",
    "plec": "Pan",
    "nazwiskoMatki": "Bradshaw",
    "rodzajDokumentuTozsamosci": "paszport",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ414926",
    "email": "moniquebradshaw@nexgene.com",
    "telefon": "(878) 520-2388",
    "wyksztalcenie": "wyższe",
    "obywatelstwo": "niemieckie",
    "narodowosc": "Seychelles"
  },
  {
    "imie": "Mcbride",
    "nazwisko": "Steele",
    "nazwiskoRodowe": "Conrad",
    "nrDomu": 2,
    "ulica": "Anna Court",
    "kod": "18-366",
    "miasto": "Denio",
    "dataUrodzenia": "24.12.1960",
    "miejsceUrodzenia": "Homeland",
    "PESEL": 92031714467,
    "NIP": 7640549604,
    "imieOjca": "Manning",
    "imieMatki": "Rebekah",
    "plec": "Pani",
    "nazwiskoMatki": "Beasley",
    "rodzajDokumentuTozsamosci": "dowod osobisty",
    "wydanyPrzez": "BurmistrzZ",
    "nrDokumentu": "XYZ575600",
    "email": "rebekahbeasley@nexgene.com",
    "telefon": "(899) 477-2135",
    "wyksztalcenie": "gimnazjalne",
    "obywatelstwo": "polskie",
    "narodowosc": "Svalbard and Jan Mayen Islands"
  },
  {
    "imie": "Hubbard",
    "nazwisko": "Barrera",
    "nazwiskoRodowe": "Norris",
    "nrDomu": 110,
    "ulica": "Virginia Place",
    "kod": "66-419",
    "miasto": "Grantville",
    "dataUrodzenia": "27.11.2009",
    "miejsceUrodzenia": "Riverton",
    "PESEL": 69043053599,
    "NIP": 6989780193,
    "imieOjca": "Castaneda",
    "imieMatki": "Acevedo",
    "plec": "Pani",
    "nazwiskoMatki": "Wong",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzX",
    "nrDokumentu": "XYZ484327",
    "email": "acevedowong@nexgene.com",
    "telefon": "(941) 408-3714",
    "wyksztalcenie": "średnie",
    "obywatelstwo": "francuskie",
    "narodowosc": "Virgin Islands (US)"
  },
  {
    "imie": "Bush",
    "nazwisko": "Wilcox",
    "nazwiskoRodowe": "Wells",
    "nrDomu": 127,
    "ulica": "Harrison Avenue",
    "kod": "44-474",
    "miasto": "Breinigsville",
    "dataUrodzenia": "3.11.1940",
    "miejsceUrodzenia": "Dale",
    "PESEL": 97011035033,
    "NIP": 3558749083,
    "imieOjca": "Orr",
    "imieMatki": "Valarie",
    "plec": "Pan",
    "nazwiskoMatki": "Walsh",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzZ",
    "nrDokumentu": "XYZ940834",
    "email": "valariewalsh@nexgene.com",
    "telefon": "(853) 533-3405",
    "wyksztalcenie": "podstawowe",
    "obywatelstwo": "polskie",
    "narodowosc": "Armenia"
  },
  {
    "imie": "Alexander",
    "nazwisko": "Patrick",
    "nazwiskoRodowe": "Melendez",
    "nrDomu": 175,
    "ulica": "Kosciusko Street",
    "kod": "98-309",
    "miasto": "Lithium",
    "dataUrodzenia": "30.10.1943",
    "miejsceUrodzenia": "Cedarville",
    "PESEL": 69031373905,
    "NIP": 5006923719,
    "imieOjca": "Luann",
    "imieMatki": "Swanson",
    "plec": "Pani",
    "nazwiskoMatki": "Gilmore",
    "rodzajDokumentuTozsamosci": "paszport",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ632835",
    "email": "swansongilmore@nexgene.com",
    "telefon": "(907) 579-2539",
    "wyksztalcenie": "gimnazjalne",
    "obywatelstwo": "francuskie",
    "narodowosc": "Djibouti"
  },
  {
    "imie": "Lyons",
    "nazwisko": "Wiggins",
    "nazwiskoRodowe": "Greer",
    "nrDomu": 23,
    "ulica": "Stuyvesant Avenue",
    "kod": "84-343",
    "miasto": "Jenkinsville",
    "dataUrodzenia": "24.12.2014",
    "miejsceUrodzenia": "Knowlton",
    "PESEL": 91011616883,
    "NIP": 2583288362,
    "imieOjca": "Whitaker",
    "imieMatki": "Dina",
    "plec": "Pan",
    "nazwiskoMatki": "Golden",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ474091",
    "email": "dinagolden@nexgene.com",
    "telefon": "(932) 512-3944",
    "wyksztalcenie": "zasadnicze zawodowe",
    "obywatelstwo": "polskie",
    "narodowosc": "Estonia"
  },
  {
    "imie": "Martinez",
    "nazwisko": "Sandoval",
    "nazwiskoRodowe": "Kim",
    "nrDomu": 185,
    "ulica": "Alton Place",
    "kod": "16-138",
    "miasto": "Morgandale",
    "dataUrodzenia": "29.12.1946",
    "miejsceUrodzenia": "Byrnedale",
    "PESEL": 92062852103,
    "NIP": 1323961985,
    "imieOjca": "Harriet",
    "imieMatki": "Allison",
    "plec": "Pan",
    "nazwiskoMatki": "Higgins",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzX",
    "nrDokumentu": "XYZ381632",
    "email": "allisonhiggins@nexgene.com",
    "telefon": "(822) 470-3936",
    "wyksztalcenie": "zasadnicze zawodowe",
    "obywatelstwo": "niemieckie",
    "narodowosc": "Marshall Islands"
  },
  {
    "imie": "Amie",
    "nazwisko": "Mosley",
    "nazwiskoRodowe": "Cochran",
    "nrDomu": 57,
    "ulica": "Congress Street",
    "kod": "48-168",
    "miasto": "Choctaw",
    "dataUrodzenia": "23.10.1932",
    "miejsceUrodzenia": "Sisquoc",
    "PESEL": 97082864550,
    "NIP": 4146652440,
    "imieOjca": "Beverly",
    "imieMatki": "Jamie",
    "plec": "Pan",
    "nazwiskoMatki": "Fleming",
    "rodzajDokumentuTozsamosci": "paszport",
    "wydanyPrzez": "BurmistrzZ",
    "nrDokumentu": "XYZ515536",
    "email": "jamiefleming@nexgene.com",
    "telefon": "(901) 530-3703",
    "wyksztalcenie": "średnie",
    "obywatelstwo": "polskie",
    "narodowosc": "Oman"
  },
  {
    "imie": "Ross",
    "nazwisko": "Martinez",
    "nazwiskoRodowe": "Wolfe",
    "nrDomu": 16,
    "ulica": "Applegate Court",
    "kod": "94-619",
    "miasto": "Westwood",
    "dataUrodzenia": "17.10.1982",
    "miejsceUrodzenia": "Ada",
    "PESEL": 52052849551,
    "NIP": 9805174524,
    "imieOjca": "Lupe",
    "imieMatki": "Hilary",
    "plec": "Pani",
    "nazwiskoMatki": "Skinner",
    "rodzajDokumentuTozsamosci": "dowod osobisty",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ769767",
    "email": "hilaryskinner@nexgene.com",
    "telefon": "(838) 415-3565",
    "wyksztalcenie": "zasadnicze zawodowe",
    "obywatelstwo": "francuskie",
    "narodowosc": "Vanuatu"
  },
  {
    "imie": "Terri",
    "nazwisko": "Collier",
    "nazwiskoRodowe": "Morgan",
    "nrDomu": 112,
    "ulica": "Beard Street",
    "kod": "31-635",
    "miasto": "Roeville",
    "dataUrodzenia": "24.10.1922",
    "miejsceUrodzenia": "Yogaville",
    "PESEL": 41052384844,
    "NIP": 7797554295,
    "imieOjca": "Bridgette",
    "imieMatki": "Hopper",
    "plec": "Pan",
    "nazwiskoMatki": "Pace",
    "rodzajDokumentuTozsamosci": "dowod osobisty",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ707895",
    "email": "hopperpace@nexgene.com",
    "telefon": "(949) 522-3793",
    "wyksztalcenie": "wyższe",
    "obywatelstwo": "polskie",
    "narodowosc": "Saint Vincent and The Grenadines"
  },
  {
    "imie": "Tabitha",
    "nazwisko": "Carter",
    "nazwiskoRodowe": "Boone",
    "nrDomu": 100,
    "ulica": "Debevoise Street",
    "kod": "62-598",
    "miasto": "Noxen",
    "dataUrodzenia": "23.12.2010",
    "miejsceUrodzenia": "Rivera",
    "PESEL": 46032462940,
    "NIP": 8723267429,
    "imieOjca": "Abby",
    "imieMatki": "Lynne",
    "plec": "Pani",
    "nazwiskoMatki": "Sweeney",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzX",
    "nrDokumentu": "XYZ584332",
    "email": "lynnesweeney@nexgene.com",
    "telefon": "(849) 586-3523",
    "wyksztalcenie": "wyższe",
    "obywatelstwo": "polskie",
    "narodowosc": "Gambia"
  },
  {
    "imie": "Cardenas",
    "nazwisko": "Ruiz",
    "nazwiskoRodowe": "Nolan",
    "nrDomu": 127,
    "ulica": "Franklin Street",
    "kod": "25-465",
    "miasto": "Rowe",
    "dataUrodzenia": "26.10.1928",
    "miejsceUrodzenia": "Coaldale",
    "PESEL": 16011370429,
    "NIP": 5124603322,
    "imieOjca": "Carver",
    "imieMatki": "Cobb",
    "plec": "Pan",
    "nazwiskoMatki": "Fulton",
    "rodzajDokumentuTozsamosci": "dowod osobisty",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ102443",
    "email": "cobbfulton@nexgene.com",
    "telefon": "(838) 529-3921",
    "wyksztalcenie": "podstawowe",
    "obywatelstwo": "polskie",
    "narodowosc": "Viet Nam"
  },
  {
    "imie": "Hicks",
    "nazwisko": "Livingston",
    "nazwiskoRodowe": "Winters",
    "nrDomu": 114,
    "ulica": "Montauk Avenue",
    "kod": "65-929",
    "miasto": "Blanco",
    "dataUrodzenia": "7.11.1961",
    "miejsceUrodzenia": "Abrams",
    "PESEL": 55091786096,
    "NIP": 6141403045,
    "imieOjca": "Kitty",
    "imieMatki": "Sims",
    "plec": "Pan",
    "nazwiskoMatki": "Ramirez",
    "rodzajDokumentuTozsamosci": "dowod osobisty",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ532790",
    "email": "simsramirez@nexgene.com",
    "telefon": "(952) 574-3298",
    "wyksztalcenie": "podstawowe",
    "obywatelstwo": "polskie",
    "narodowosc": "Zimbabwe"
  },
  {
    "imie": "Tabatha",
    "nazwisko": "Hudson",
    "nazwiskoRodowe": "Waller",
    "nrDomu": 18,
    "ulica": "Coles Street",
    "kod": "90-574",
    "miasto": "Albrightsville",
    "dataUrodzenia": "26.12.2007",
    "miejsceUrodzenia": "Esmont",
    "PESEL": 94022834383,
    "NIP": 9179246690,
    "imieOjca": "Giles",
    "imieMatki": "Warner",
    "plec": "Pan",
    "nazwiskoMatki": "Quinn",
    "rodzajDokumentuTozsamosci": "paszport",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ469854",
    "email": "warnerquinn@nexgene.com",
    "telefon": "(860) 509-2926",
    "wyksztalcenie": "podstawowe",
    "obywatelstwo": "polskie",
    "narodowosc": "British Indian Ocean Territory"
  },
  {
    "imie": "Leann",
    "nazwisko": "Chapman",
    "nazwiskoRodowe": "Cardenas",
    "nrDomu": 80,
    "ulica": "Linden Boulevard",
    "kod": "60-926",
    "miasto": "Templeton",
    "dataUrodzenia": "29.11.1951",
    "miejsceUrodzenia": "Tooleville",
    "PESEL": 92091075023,
    "NIP": 1552646281,
    "imieOjca": "Reyes",
    "imieMatki": "Wood",
    "plec": "Pan",
    "nazwiskoMatki": "Meyers",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzZ",
    "nrDokumentu": "XYZ435859",
    "email": "woodmeyers@nexgene.com",
    "telefon": "(851) 421-3899",
    "wyksztalcenie": "średnie",
    "obywatelstwo": "niemieckie",
    "narodowosc": "Netherlands Antilles"
  },
  {
    "imie": "Maria",
    "nazwisko": "Whitfield",
    "nazwiskoRodowe": "Dickerson",
    "nrDomu": 54,
    "ulica": "Ferris Street",
    "kod": "37-736",
    "miasto": "Valle",
    "dataUrodzenia": "30.10.1958",
    "miejsceUrodzenia": "Jugtown",
    "PESEL": 82031552645,
    "NIP": 9163441777,
    "imieOjca": "Pacheco",
    "imieMatki": "Rosario",
    "plec": "Pani",
    "nazwiskoMatki": "Huber",
    "rodzajDokumentuTozsamosci": "dowod osobisty",
    "wydanyPrzez": "BurmistrzZ",
    "nrDokumentu": "XYZ179488",
    "email": "rosariohuber@nexgene.com",
    "telefon": "(888) 551-3046",
    "wyksztalcenie": "wyższe",
    "obywatelstwo": "polskie",
    "narodowosc": "Belarus"
  },
  {
    "imie": "Odessa",
    "nazwisko": "Suarez",
    "nazwiskoRodowe": "Raymond",
    "nrDomu": 32,
    "ulica": "Royce Street",
    "kod": "55-323",
    "miasto": "Olney",
    "dataUrodzenia": "15.11.1999",
    "miejsceUrodzenia": "Fivepointville",
    "PESEL": 48032177853,
    "NIP": 3834952140,
    "imieOjca": "Cleveland",
    "imieMatki": "Gaines",
    "plec": "Pan",
    "nazwiskoMatki": "Hewitt",
    "rodzajDokumentuTozsamosci": "dowod osobisty",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ977503",
    "email": "gaineshewitt@nexgene.com",
    "telefon": "(952) 418-2037",
    "wyksztalcenie": "średnie",
    "obywatelstwo": "polskie",
    "narodowosc": "Belize"
  },
  {
    "imie": "Perkins",
    "nazwisko": "Maxwell",
    "nazwiskoRodowe": "Erickson",
    "nrDomu": 57,
    "ulica": "Williamsburg Street",
    "kod": "96-542",
    "miasto": "Wyano",
    "dataUrodzenia": "5.12.1905",
    "miejsceUrodzenia": "Deltaville",
    "PESEL": 25053021680,
    "NIP": 1014475531,
    "imieOjca": "Kerri",
    "imieMatki": "Dolly",
    "plec": "Pani",
    "nazwiskoMatki": "Giles",
    "rodzajDokumentuTozsamosci": "dowod osobisty",
    "wydanyPrzez": "BurmistrzZ",
    "nrDokumentu": "XYZ463795",
    "email": "dollygiles@nexgene.com",
    "telefon": "(921) 560-2106",
    "wyksztalcenie": "wyższe",
    "obywatelstwo": "francuskie",
    "narodowosc": "Maldives"
  },
  {
    "imie": "Ramirez",
    "nazwisko": "Dominguez",
    "nazwiskoRodowe": "Houston",
    "nrDomu": 63,
    "ulica": "Farragut Place",
    "kod": "92-857",
    "miasto": "Gilmore",
    "dataUrodzenia": "15.11.1988",
    "miejsceUrodzenia": "Kieler",
    "PESEL": 27072257114,
    "NIP": 2485989656,
    "imieOjca": "Candace",
    "imieMatki": "Guadalupe",
    "plec": "Pani",
    "nazwiskoMatki": "Allison",
    "rodzajDokumentuTozsamosci": "paszport",
    "wydanyPrzez": "BurmistrzX",
    "nrDokumentu": "XYZ499746",
    "email": "guadalupeallison@nexgene.com",
    "telefon": "(930) 547-3270",
    "wyksztalcenie": "gimnazjalne",
    "obywatelstwo": "francuskie",
    "narodowosc": "Hong Kong"
  },
  {
    "imie": "Willis",
    "nazwisko": "Hart",
    "nazwiskoRodowe": "Daniel",
    "nrDomu": 118,
    "ulica": "Sheffield Avenue",
    "kod": "98-433",
    "miasto": "Rosine",
    "dataUrodzenia": "30.12.1926",
    "miejsceUrodzenia": "Westmoreland",
    "PESEL": 79072262387,
    "NIP": 7495451632,
    "imieOjca": "Terrie",
    "imieMatki": "Lakeisha",
    "plec": "Pan",
    "nazwiskoMatki": "Simpson",
    "rodzajDokumentuTozsamosci": "paszport",
    "wydanyPrzez": "BurmistrzX",
    "nrDokumentu": "XYZ767540",
    "email": "lakeishasimpson@nexgene.com",
    "telefon": "(980) 427-3909",
    "wyksztalcenie": "gimnazjalne",
    "obywatelstwo": "polskie",
    "narodowosc": "Guyana"
  },
  {
    "imie": "Jane",
    "nazwisko": "Briggs",
    "nazwiskoRodowe": "Knox",
    "nrDomu": 5,
    "ulica": "Mill Road",
    "kod": "69-974",
    "miasto": "Hiko",
    "dataUrodzenia": "10.10.1994",
    "miejsceUrodzenia": "Clara",
    "PESEL": 17092766822,
    "NIP": 1123395849,
    "imieOjca": "Cleo",
    "imieMatki": "Suarez",
    "plec": "Pan",
    "nazwiskoMatki": "Horton",
    "rodzajDokumentuTozsamosci": "dowod osobisty",
    "wydanyPrzez": "BurmistrzX",
    "nrDokumentu": "XYZ366824",
    "email": "suarezhorton@nexgene.com",
    "telefon": "(823) 547-3517",
    "wyksztalcenie": "gimnazjalne",
    "obywatelstwo": "francuskie",
    "narodowosc": "Faroe Islands"
  },
  {
    "imie": "Clemons",
    "nazwisko": "Cruz",
    "nazwiskoRodowe": "Velez",
    "nrDomu": 95,
    "ulica": "Branton Street",
    "kod": "63-854",
    "miasto": "Dixie",
    "dataUrodzenia": "11.11.1965",
    "miejsceUrodzenia": "Torboy",
    "PESEL": 53081342676,
    "NIP": 2683199893,
    "imieOjca": "Whitley",
    "imieMatki": "Nell",
    "plec": "Pani",
    "nazwiskoMatki": "Camacho",
    "rodzajDokumentuTozsamosci": "paszport",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ302711",
    "email": "nellcamacho@nexgene.com",
    "telefon": "(818) 407-2955",
    "wyksztalcenie": "gimnazjalne",
    "obywatelstwo": "polskie",
    "narodowosc": "Togo"
  },
  {
    "imie": "Lesley",
    "nazwisko": "Head",
    "nazwiskoRodowe": "Burgess",
    "nrDomu": 7,
    "ulica": "Seeley Street",
    "kod": "18-618",
    "miasto": "Roosevelt",
    "dataUrodzenia": "4.10.2004",
    "miejsceUrodzenia": "Chesterfield",
    "PESEL": 84051167094,
    "NIP": 5478352235,
    "imieOjca": "Millie",
    "imieMatki": "Brandy",
    "plec": "Pani",
    "nazwiskoMatki": "Vance",
    "rodzajDokumentuTozsamosci": "dowod osobisty",
    "wydanyPrzez": "BurmistrzZ",
    "nrDokumentu": "XYZ229485",
    "email": "brandyvance@nexgene.com",
    "telefon": "(920) 577-2668",
    "wyksztalcenie": "wyższe",
    "obywatelstwo": "polskie",
    "narodowosc": "Trinidad and Tobago"
  },
  {
    "imie": "Cora",
    "nazwisko": "Shannon",
    "nazwiskoRodowe": "Harrington",
    "nrDomu": 6,
    "ulica": "Loring Avenue",
    "kod": "62-840",
    "miasto": "Catharine",
    "dataUrodzenia": "7.11.1969",
    "miejsceUrodzenia": "Lindcove",
    "PESEL": 18042899819,
    "NIP": 6466505582,
    "imieOjca": "Marta",
    "imieMatki": "Jacobson",
    "plec": "Pani",
    "nazwiskoMatki": "Heath",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzX",
    "nrDokumentu": "XYZ598004",
    "email": "jacobsonheath@nexgene.com",
    "telefon": "(877) 582-3906",
    "wyksztalcenie": "gimnazjalne",
    "obywatelstwo": "francuskie",
    "narodowosc": "Italy"
  },
  {
    "imie": "Karen",
    "nazwisko": "Guerrero",
    "nazwiskoRodowe": "Vega",
    "nrDomu": 189,
    "ulica": "Catherine Street",
    "kod": "11-262",
    "miasto": "Sheatown",
    "dataUrodzenia": "20.11.1996",
    "miejsceUrodzenia": "Benson",
    "PESEL": 81081348060,
    "NIP": 2429209546,
    "imieOjca": "Gilmore",
    "imieMatki": "Kellie",
    "plec": "Pani",
    "nazwiskoMatki": "Moses",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzX",
    "nrDokumentu": "XYZ917578",
    "email": "kelliemoses@nexgene.com",
    "telefon": "(977) 543-3947",
    "wyksztalcenie": "gimnazjalne",
    "obywatelstwo": "francuskie",
    "narodowosc": "United Arab Emirates"
  },
  {
    "imie": "Larsen",
    "nazwisko": "Coffey",
    "nazwiskoRodowe": "Joyce",
    "nrDomu": 140,
    "ulica": "Oriental Court",
    "kod": "39-869",
    "miasto": "Clarktown",
    "dataUrodzenia": "5.12.2012",
    "miejsceUrodzenia": "Montura",
    "PESEL": 76072199978,
    "NIP": 8181990825,
    "imieOjca": "Marcella",
    "imieMatki": "Michelle",
    "plec": "Pan",
    "nazwiskoMatki": "Diaz",
    "rodzajDokumentuTozsamosci": "paszport",
    "wydanyPrzez": "BurmistrzX",
    "nrDokumentu": "XYZ626466",
    "email": "michellediaz@nexgene.com",
    "telefon": "(861) 416-2925",
    "wyksztalcenie": "średnie",
    "obywatelstwo": "francuskie",
    "narodowosc": "Myanmar"
  },
  {
    "imie": "Gardner",
    "nazwisko": "Hyde",
    "nazwiskoRodowe": "Gonzales",
    "nrDomu": 87,
    "ulica": "Gatling Place",
    "kod": "96-341",
    "miasto": "Driftwood",
    "dataUrodzenia": "29.12.1952",
    "miejsceUrodzenia": "Fresno",
    "PESEL": 24031516792,
    "NIP": 2212190888,
    "imieOjca": "Louise",
    "imieMatki": "Serena",
    "plec": "Pan",
    "nazwiskoMatki": "Wooten",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ134359",
    "email": "serenawooten@nexgene.com",
    "telefon": "(811) 479-3147",
    "wyksztalcenie": "zasadnicze zawodowe",
    "obywatelstwo": "niemieckie",
    "narodowosc": "Bolivia"
  },
  {
    "imie": "Harper",
    "nazwisko": "Haney",
    "nazwiskoRodowe": "Branch",
    "nrDomu": 87,
    "ulica": "Meeker Avenue",
    "kod": "81-219",
    "miasto": "Seymour",
    "dataUrodzenia": "20.12.2011",
    "miejsceUrodzenia": "Cecilia",
    "PESEL": 56061070930,
    "NIP": 5346730860,
    "imieOjca": "Barker",
    "imieMatki": "Alisha",
    "plec": "Pani",
    "nazwiskoMatki": "Ryan",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ360268",
    "email": "alisharyan@nexgene.com",
    "telefon": "(852) 567-3953",
    "wyksztalcenie": "wyższe",
    "obywatelstwo": "francuskie",
    "narodowosc": "El Salvador"
  },
  {
    "imie": "Madge",
    "nazwisko": "Garrison",
    "nazwiskoRodowe": "Castillo",
    "nrDomu": 170,
    "ulica": "Duryea Place",
    "kod": "21-109",
    "miasto": "Shelby",
    "dataUrodzenia": "10.12.2014",
    "miejsceUrodzenia": "Gorst",
    "PESEL": 47011287028,
    "NIP": 5309885837,
    "imieOjca": "Lauri",
    "imieMatki": "Guerrero",
    "plec": "Pani",
    "nazwiskoMatki": "Hammond",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzX",
    "nrDokumentu": "XYZ301635",
    "email": "guerrerohammond@nexgene.com",
    "telefon": "(903) 487-2452",
    "wyksztalcenie": "wyższe",
    "obywatelstwo": "niemieckie",
    "narodowosc": "Gabon"
  },
  {
    "imie": "Workman",
    "nazwisko": "Johnson",
    "nazwiskoRodowe": "Anderson",
    "nrDomu": 44,
    "ulica": "Garland Court",
    "kod": "30-253",
    "miasto": "Loyalhanna",
    "dataUrodzenia": "2.12.1929",
    "miejsceUrodzenia": "Independence",
    "PESEL": 16012518401,
    "NIP": 2532528620,
    "imieOjca": "Harrington",
    "imieMatki": "Beulah",
    "plec": "Pan",
    "nazwiskoMatki": "Sparks",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzX",
    "nrDokumentu": "XYZ108277",
    "email": "beulahsparks@nexgene.com",
    "telefon": "(845) 489-2381",
    "wyksztalcenie": "podstawowe",
    "obywatelstwo": "francuskie",
    "narodowosc": "Uruguay"
  },
  {
    "imie": "Franklin",
    "nazwisko": "Rowland",
    "nazwiskoRodowe": "Small",
    "nrDomu": 69,
    "ulica": "Jamaica Avenue",
    "kod": "25-374",
    "miasto": "Utting",
    "dataUrodzenia": "7.11.1940",
    "miejsceUrodzenia": "Norfolk",
    "PESEL": 33061097128,
    "NIP": 7556668309,
    "imieOjca": "Milagros",
    "imieMatki": "Raquel",
    "plec": "Pan",
    "nazwiskoMatki": "Tillman",
    "rodzajDokumentuTozsamosci": "paszport",
    "wydanyPrzez": "BurmistrzZ",
    "nrDokumentu": "XYZ435850",
    "email": "raqueltillman@nexgene.com",
    "telefon": "(826) 531-2599",
    "wyksztalcenie": "średnie",
    "obywatelstwo": "francuskie",
    "narodowosc": "Honduras"
  },
  {
    "imie": "Rita",
    "nazwisko": "Massey",
    "nazwiskoRodowe": "Murray",
    "nrDomu": 150,
    "ulica": "Classon Avenue",
    "kod": "63-397",
    "miasto": "Whitewater",
    "dataUrodzenia": "19.10.1921",
    "miejsceUrodzenia": "Jennings",
    "PESEL": 70041444808,
    "NIP": 2905046412,
    "imieOjca": "Mcdaniel",
    "imieMatki": "Holly",
    "plec": "Pan",
    "nazwiskoMatki": "Jackson",
    "rodzajDokumentuTozsamosci": "dowod osobisty",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ917551",
    "email": "hollyjackson@nexgene.com",
    "telefon": "(982) 573-3459",
    "wyksztalcenie": "podstawowe",
    "obywatelstwo": "francuskie",
    "narodowosc": "Suriname"
  },
  {
    "imie": "Veronica",
    "nazwisko": "Rosales",
    "nazwiskoRodowe": "Buckley",
    "nrDomu": 90,
    "ulica": "Strong Place",
    "kod": "85-704",
    "miasto": "Finderne",
    "dataUrodzenia": "14.10.1913",
    "miejsceUrodzenia": "Edgewater",
    "PESEL": 40032942140,
    "NIP": 9549398029,
    "imieOjca": "Leonard",
    "imieMatki": "Park",
    "plec": "Pani",
    "nazwiskoMatki": "Key",
    "rodzajDokumentuTozsamosci": "dowod osobisty",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ191611",
    "email": "parkkey@nexgene.com",
    "telefon": "(934) 597-3209",
    "wyksztalcenie": "gimnazjalne",
    "obywatelstwo": "francuskie",
    "narodowosc": "French Polynesia"
  },
  {
    "imie": "Sanders",
    "nazwisko": "Blair",
    "nazwiskoRodowe": "Mcintosh",
    "nrDomu": 166,
    "ulica": "Sullivan Place",
    "kod": "39-299",
    "miasto": "Weeksville",
    "dataUrodzenia": "17.11.1958",
    "miejsceUrodzenia": "Masthope",
    "PESEL": 12022092800,
    "NIP": 1217440681,
    "imieOjca": "Eileen",
    "imieMatki": "Riddle",
    "plec": "Pan",
    "nazwiskoMatki": "Roach",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ735114",
    "email": "riddleroach@nexgene.com",
    "telefon": "(987) 552-2889",
    "wyksztalcenie": "wyższe",
    "obywatelstwo": "polskie",
    "narodowosc": "Antarctica"
  },
  {
    "imie": "Whitfield",
    "nazwisko": "Ochoa",
    "nazwiskoRodowe": "Wilkins",
    "nrDomu": 12,
    "ulica": "Madison Street",
    "kod": "76-571",
    "miasto": "Eureka",
    "dataUrodzenia": "26.12.1994",
    "miejsceUrodzenia": "Loma",
    "PESEL": 93082497267,
    "NIP": 3106763717,
    "imieOjca": "Parrish",
    "imieMatki": "Young",
    "plec": "Pan",
    "nazwiskoMatki": "Foley",
    "rodzajDokumentuTozsamosci": "prawo jazdy",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ499301",
    "email": "youngfoley@nexgene.com",
    "telefon": "(951) 566-2038",
    "wyksztalcenie": "podstawowe",
    "obywatelstwo": "polskie",
    "narodowosc": "Aruba"
  },
  {
    "imie": "Delores",
    "nazwisko": "Gaines",
    "nazwiskoRodowe": "Berry",
    "nrDomu": 75,
    "ulica": "Prospect Avenue",
    "kod": "58-390",
    "miasto": "Hasty",
    "dataUrodzenia": "3.10.2005",
    "miejsceUrodzenia": "Davenport",
    "PESEL": 42082999770,
    "NIP": 5613756322,
    "imieOjca": "Sears",
    "imieMatki": "Maritza",
    "plec": "Pan",
    "nazwiskoMatki": "Harding",
    "rodzajDokumentuTozsamosci": "dowod osobisty",
    "wydanyPrzez": "BurmistrzY",
    "nrDokumentu": "XYZ236629",
    "email": "maritzaharding@nexgene.com",
    "telefon": "(858) 511-2284",
    "wyksztalcenie": "gimnazjalne",
    "obywatelstwo": "polskie",
    "narodowosc": "Guatemala"
  }
]};